### ISSUE TITLE
Tests are currently broken

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#231]
Here are the failures:
https://amplab.cs.berkeley.edu/jenkins/view/E-Mission/job/e-mission-server/105/console

Please
* delete your current branch
* pull from upstream
* create a new branch

and make the fixes in there.

Please make the changes ASAP so that the build is not red for a long time.

```
======================================================================
ERROR: testBinData (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 48, in testBinData
    sim = similarity.similarity([], 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testDeleteBins (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 81, in testDeleteBins
    sim = similarity.similarity(self.data, 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testDistance (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 115, in testDistance
    sim = similarity.similarity(self.data, 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testEvaluateBins (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 135, in testEvaluateBins
    sim = similarity.similarity([], 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testGraph (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 122, in testGraph
    sim = similarity.similarity([], 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testInit (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 36, in testInit
    sim = similarity.similarity([], 100)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testMatch (analysisTests.TestSimilarity.SimilarityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestSimilarity.py", line 101, in testMatch
    sim = similarity.similarity(self.data, 300)
  File "emission/analysis/modelling/tour_model/similarity.py", line 56, in __init__
    if self.distance(start_lat, start_lon, end_lat, end_lon):
UnboundLocalError: local variable 'start_lat' referenced before assignment

======================================================================
ERROR: testEveryThing (analysisTests.TestClusterPipeline.ClusterPipelineTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/TestClusterPipeline.py", line 23, in testEveryThing
    tg.create_fake_trips(user_name)
  File "emission/simulation/trip_gen.py", line 173, in create_fake_trips
    my_creator.get_trips_from_a_to_b(user_name)
  File "emission/simulation/trip_gen.py", line 94, in get_trips_from_a_to_b
    save_trip_to_db(alt_trip)
  File "emission/simulation/trip_gen.py", line 111, in save_trip_to_db
    "trip_end_location": trip.trip_end_location.coordinate_list(), "mode_list": trip.mode_list})
  File "/home/anaconda/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <analysisTests.TestClusterPipeline.ClusterPipelineTests testMethod=testEveryThing>

======================================================================
FAIL: testEntirePipeline (analysisTests.modeinferTests.TestPipeline.TestPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server/emission/tests/analysisTests/modeinferTests/TestPipeline.py", line 274, in testEntirePipeline
    self.assertEquals(test_id_1_sec['predicted_mode'], {'walking': 1})
AssertionError: {u'bus': 0.1, u'walking': 0.9} != {'walking': 1}
- {u'bus': 0.1, u'walking': 0.9}
+ {'walking': 1}

----------------------------------------------------------------------
Ran 276 tests in 596.392s
```

**Comment by shankari** [comment]
I have fixed this now.
