### ISSUE TITLE
Trips are looked up twice from the database in the new tour model code

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#247]
First, we get all the trips from the database.

```
    if not old:
        logging.debug("not old")
        db = edb.get_trip_new_db()
        trips = db.find({"user_id" : uuid})
```

Then, we convert them to ids

```
return [trip["_id"] for trip in trips]
```

And then we look up the trips again individually in the featurization constructor.

It looks like for the old version, we pass the trips around directly. Why can't we do that again? Why do we need to convert them to ids and then re-read the trips for the IDs?

Currently, we open the database for every read of a single trip, 
```
def get_trip(trip_id):
    """
    Returns the trip for specified trip id.
    :rtype : emission.core.wrapper.Trip
    """
    return ecwt.Trip(edb.get_trip_new_db().find_one({"_id": trip_id}))
```
and opening the database multiple times in quick succession causes a crash.

```
Traceback (most recent call last):
  File "bin/intake_stage.py", line 48, in <module>
    esdtmq.make_tour_model_from_raw_user_data(uuid)
  File "/mnt/e-mission/e-mission-server/emission/storage/decorations/tour_model_queries.py", line 50, in make_tour_model_from_raw_user_data
    list_of_cluster_data = eamtmcp.main(user_id, False)
  File "/mnt/e-mission/e-mission-server/emission/analysis/modelling/tour_model/cluster_pipeline.py", line 106, in main
    n, labels, data = cluster(data, len(bins), old=old)
  File "/mnt/e-mission/e-mission-server/emission/analysis/modelling/tour_model/cluster_pipeline.py", line 83, in cluster
    feat = featurization.featurization(data, old=old)
  File "/mnt/e-mission/e-mission-server/emission/analysis/modelling/tour_model/featurization.py", line 33, in __init__
    self.calculate_points()
  File "/mnt/e-mission/e-mission-server/emission/analysis/modelling/tour_model/featurization.py", line 48, in calculate_points
    trip = esdtq.get_trip(trip)
  File "/mnt/e-mission/e-mission-server/emission/storage/decorations/trip_queries.py", line 43, in get_trip
    return ecwt.Trip(edb.get_trip_new_db().find_one({"_id": trip_id}))
  File "/mnt/e-mission/e-mission-server/emission/core/get_database.py", line 183, in get_trip_new_db
    current_db = MongoClient().Stage_database
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 99] Cannot assign requested address
```

**Comment by joshzarrabi** [comment]
I thought this was better  style given the new classes

**Comment by shankari** [comment]
I'm not sure I understand why. The new classes have trip objects, so why not just keep the trip objects and pass them around instead of converting them to ids? In fact, the trip and section objects now are much smaller than the previous versions.

**Comment by joshzarrabi** [comment]
Okay

**Comment by shankari** [comment]
Fixed by https://github.com/e-mission/e-mission-server/pull/248
