### ISSUE TITLE
Trips are sometimes incorrectly "joined" even if the gap between sections is close to an hour long

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#352]
We have just started our trip, yay! Now we still don't have enough points to make a decision.

```
2016-08-15 12:10:17,370:DEBUG:------------------------------2016-08-10T09:54:31-07:00------------------------------
2016-08-15 12:10:17,372:DEBUG:last5MinsDistances = [ 52.82764235] with length 1
2016-08-15 12:10:17,374:DEBUG:last10PointsDistances = [ 52.82764235   0.        ] with length 2, shape (2,)
2016-08-15 12:10:17,374:DEBUG:len(last10PointsDistances) = 2, len(last5MinsDistances) = 1
2016-08-15 12:10:17,375:DEBUG:last5MinsTimes.max() = 31.5750000477, time_threshold = 300
2016-08-15 12:10:17,375:DEBUG:Too few points to make a decision, continuing
...
2016-08-15 12:10:17,435:DEBUG:------------------------------2016-08-10T09:58:13-07:00------------------------------
2016-08-15 12:10:17,440:DEBUG:last5MinsDistances = [ 329.2908086   280.89265787  245.2010695   184.71648394  189.02429048
  142.74543776   87.77772771   43.01575703   56.99527453] with length 9
2016-08-15 12:10:17,444:DEBUG:last10PointsDistances = [ 329.2908086   280.89265787  245.2010695   184.71648394  189.02429048
  142.74543776   87.77772771   43.01575703   56.99527453    0.        ] with length 10, shape (10,)
2016-08-15 12:10:17,446:DEBUG:len(last10PointsDistances) = 10, len(last5MinsDistances) = 9
2016-08-15 12:10:17,446:DEBUG:last5MinsTimes.max() = 253.575000048, time_threshold = 300
2016-08-15 12:10:17,447:DEBUG:Too few points to make a decision, continuing
```

Now we finally have enough points

```
2016-08-15 12:10:17,447:DEBUG:------------------------------2016-08-10T09:58:52-07:00------------------------------
2016-08-15 12:10:17,454:DEBUG:last5MinsDistances = [ 368.82243137  323.60485982  289.21766655  230.01780163  235.70421315
  192.31601923  144.97574662   96.48072959   89.58728643   59.109117  ] with length 10
2016-08-15 12:10:17,457:DEBUG:last10PointsDistances = [ 323.60485982  289.21766655  230.01780163  235.70421315  192.31601923
  144.97574662   96.48072959   89.58728643   59.109117      0.        ] with length 10, shape (10,)
2016-08-15 12:10:17,460:DEBUG:len(last10PointsDistances) = 10, len(last5MinsDistances) = 10
2016-08-15 12:10:17,461:DEBUG:last5MinsTimes.max() = 292.575000048, time_threshold = 300
2016-08-15 12:10:17,461:DEBUG:last5MinsDistances.max() = 368.822431372, last10PointsDistance.max() = 323.604859817
...
2016-08-15 12:10:17,609:DEBUG:------------------------------2016-08-10T10:03:53-07:00------------------------------
2016-08-15 12:10:17,615:DEBUG:last5MinsDistances = [ 131.22779511  122.19976408   77.28623256   51.39123828   36.04130693
   39.82444342   25.54539197   14.229786     34.26178107   25.54539197
   36.07236258] with length 11
2016-08-15 12:10:17,619:DEBUG:last10PointsDistances = [ 77.28623256  51.39123828  36.04130693  39.82444342  25.54539197
  14.229786    34.26178107  25.54539197  36.07236258   0.        ] with length 10, shape (10,)
2016-08-15 12:10:17,622:DEBUG:len(last10PointsDistances) = 10, len(last5MinsDistances) = 11
2016-08-15 12:10:17,622:DEBUG:last5MinsTimes.max() = 271.786000013, time_threshold = 300
2016-08-15 12:10:17,622:DEBUG:last5MinsDistances.max() = 131.227795112, last10PointsDistance.max() = 77.2862325602
```

Here's where we should segment. Here, we have enough points, and the
last10PointsDistance.max() is only 77, but the last 5 mins distances > 100

And then we only get a point on the return trip.

```
2016-08-15 12:10:17,623:DEBUG:------------------------------2016-08-10T11:07:05.684000-07:00------------------------------
2016-08-15 12:10:17,625:DEBUG:last5MinsDistances = [] with length 0
2016-08-15 12:10:17,629:DEBUG:last10PointsDistances = [ 109.66159855  129.1706589   118.45003771  131.19699388  146.88650462
  122.53046402  131.19699388  120.7937173   156.72206388    0.        ] with length 10, shape (10,)
2016-08-15 12:10:17,629:DEBUG:len(last10PointsDistances) = 10, len(last5MinsDistances) = 0
```

**Comment by shankari** [comment]
The real problem is that after 34a6cef915a1c1e6f7c301a60c1116fa798c489b, there is a mismatch between the trip end detection on the phone and the server. So while the server still hasn't detected the trip end, the phone has, and has stopped getting points. So we don't get any more points on the server until we start the return trip, so we don't finish detecting the trip end.

Seems like a solution is to check not just the distance between points but also the time. If there is a sufficiently large gap in the time, then we can start a new trip.

Note though that sometimes we have large time gaps to bad accuracy points - the prime example of which is the trip to Oakland on the 11th in which we missed points for almost an hour. We need to make sure that we don't detect a trip end for that case.

One solution to distinguish between the two cases is that in one case (optometrist), the point after the gap is close to the point before the gap (so we must have been at that location all that time, so this must be a new trip). In the other case (to OAK), the point after the gap is huge, so we must have been moving during that time, so this is a trip continuation.

This should also help with other weird behavior we have seen, such as when the phone loses power - we won't end up with a trip that is walking from Berkeley to Mountain View!

**Comment by shankari** [comment]
It's a little tricky to look at the time from the "last point" because we only look at a subset of the data right now. For example, if we had got a sync from the phone at 10:20, we would not have detected the trip end, and then when we next start, we would have started with the 11:07 trip, which means that the trip there would be skipped again.

One way to fix this is to set the pipeline stage to the last segmentation point timestamp. But then, we can no longer always start a trip at point 0 because we may have a glommed on set of points at the beginning.

Couple of potential workarounds:
1. Start the trip at the first `exited geofence` transition
2. End the trip at the `trip_ended` transition even if we don't have enough points

For now, I'm going with (1) since:
a. we are not guaranteed to get a `trip_detected` in the phone is rebooted or sth.
b. what I really do manually is to look at large gaps in the points and segment there, so this is closer to my behavior as well.

but if the phone is rebooted, and we start at the first `exited geofence`
transition, we are still going to miss the section that was only halfway
complete...

well, if the battery dies and the phone is rebooted, we are not going to have a
sync immediately. We will have a sync at the end of the next complete trip, and
then the gap argument will work as well.

**Comment by shankari** [comment]
Note also that for ongoing collection, syncs are not synchronized with trip
starts and ends. So that would argue for (1) in which we set the completed
timestamp to the last completed trip end.

Note that in the continuous case, the gap strategy will never actually be
invoked since we don't stop collection on the phone, but that's OK.

In fact, without (1), trip segmentation for ongoing collection is potentially
broken...

While ongoing collection is not a huge use case, it seems like something that would
support it is a Good Thing.

**Comment by shankari** [comment]
It also looks like we have hit something before with the iOS dist filter. This does highlight that using the "processed" timestamp instead will potentially delay the detection of the trip until later. 
Our solution was to check for the transition as well, which will, of course, break in the case that there is no transition (e.g. phone was turned off).

```
        # Since we only end a trip when we start a new trip, this means that
        # the last trip that was pushed is ignored.
        ...
        # There are multiple potential fixes:
        # - we can mark only the completed trips as processed. This will solve (2) above, but not (1)
```

**Comment by shankari** [comment]
I think that we can handle this with the 80-20 rule.

1. We should only really mark points that we have processed as processed. That is almost a bug fix. If you have looked at points, but have not been able to classify them as "belonging to a trip", or need to skip, then they are unclassified, and you need to look at them next time. Note that this means that glommed on points should also be included in the list of processed points.
2. When we have finished looking at all points, if we haven't ended a trip, then:
  1. if there is a transition, end the trip
 2. else, let the points be handled during the next run

This seems to cover all cases:
- mismatch
- continuous collection
- glommed points

**Comment by shankari** [comment]
We already have a fix for 2 (i) on iOS
https://github.com/e-mission/e-mission-server/blob/master/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_dist_filter.py#L134

```
        if not just_ended and len(transition_df) > 0:
            stopped_moving_after_last = transition_df[(transition_df.ts > currPoint.ts) & (transition_df.transition == 2)]
            if len(stopped_moving_after_last) > 0:
                segmentation_points.append((curr_trip_start_point, currPoint))
return segmentation_points
```

and it works, but the next trip seems to be broken.

**Comment by shankari** [comment]
We detect a trip end at 16:56

```
2016-08-20 07:22:42,718:DEBUG:140735159468032:------------------------------2016-02-22T16:56:58.000047-08:00------------------------------
2016-08-20 07:22:42,719:DEBUG:140735159468032:lastPoint = AttrDict({u'local_dt_hour': 16, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 53, u'local_dt_year': 2016, u'local_dt_month': 2, u'local_dt_weekday': 0, u'loc': {u'type': u'Point', u'coordinates': [-122.0859086607789, 37.39164138216282]}, 'user_id': UUID('67ce6d8e-c0e0-4012-89df-bac2c91941e4'), u'floor': 0, u'altitude': 19.034328034609381, u'vaccuracy': 3.0, u'ts': 1456189013.000047, u'latitude': 37.391641382162817, u'sensed_speed': 13.260000228881839, u'accuracy': 5.0, u'fmt_time': u'2016-02-22T16:56:53.000047-08:00', u'local_dt_minute': 56, 'metadata_write_ts': 1456189013.179846, u'longitude': -122.0859086607789, u'filter': u'distance', '_id': ObjectId('56cbcb4ceaedff78c763669c'), u'heading': 206.015625, u'local_dt_day': 22}), time difference = 5.0 dist difference 56.834016686
2016-08-20 07:22:42,720:DEBUG:140735159468032:Found 2 transitions after last point, ending trip...
...
2016-08-20 07:22:42,900:INFO:140735159468032:Returning last_ts_processed = 1456189018.17
2016-08-20 07:22:42,901:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, last_ts_processed = 2016-02-23T00:57:03.174159
```

Now, we start the next run

```
2016-08-20 07:22:47,941:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2016-02-23T00:57:03.174159
```

Here's the first point. Aha! We hit #302, but on iOS.

```
2016-08-20 07:22:47,973:DEBUG:140735159468032:------------------------------2016-02-22T19:41:42.085297-08:00------------------------------
2016-08-20 07:22:47,973:DEBUG:140735159468032:Comparing with lastPoint = AttrDict({u'local_dt_hour': 20, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 15, u'local_dt_year': 2016, u'local_dt_month': 2, u'local_dt_weekday': 0, u'loc': {u'type': u'Point', u'coordinates': [-122.0863878541832, 37.39094635475184]}, 'user_id': UUID('67ce6d8e-c0e0-4012-89df-bac2c91941e4'), u'floor': 0, u'altitude': 30.109710693359379, u'vaccuracy': 3.0, u'ts': 1456200735.0000949, u'latitude': 37.39094635475184, u'sensed_speed': 0.56000000238418579, u'accuracy': 5.0, u'fmt_time': u'2016-02-22T20:12:15.000095-08:00', u'local_dt_minute': 12, 'metadata_write_ts': 1456200735.1506031, u'longitude': -122.0863878541832, u'filter': u'distance', '_id': ObjectId('56cbf571eaedff78c7636ab3'), u'heading': 319.921875, u'local_dt_day': 22}), distance = False, time = True
```

**Comment by shankari** [comment]
Even after fixing that, we get the same mismatch.

```
2016-08-20 21:33:22,549:DEBUG:140735159468032:Comparing 2016-02-22T19:41:42.085297-08:00 with 2016-02-22T19:42:49.000034-08:00
```

The separated run actually starts the trip earlier than the non-separated run.  Mapping the raw points shows that they are near the library parking lot, so they should definitely be counted. So probably the issue is with the original - let's check those logs.

Ok so here's what happens.

This is the last valid point.

```
2016-08-20 22:00:06,633:DEBUG:------------------------------2016-02-22T16:56:58.000047-08:00------------------------------
```

Next comes the start of the new trip

```
2016-08-20 22:00:06,634:DEBUG:------------------------------2016-02-22T19:41:42.085297-08:00------------------------------
```

We detect a trip end at the previous point but then we move on to the next point.

```
2016-08-20 22:00:06,636:DEBUG:Appending last_trip_end_point AttrDict({u'local_dt_hour': 16, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 58, u'local_dt_year': 2016, u'local_dt_month': 2, u'local_dt_weekday': 0, u'loc': {u'type': u'Point', u'coordinates': [-122.0861964953338, 37.39118427507336]}, 'user_id': UUID('079e0f1a-c440-3d7c-b0e7-de160f748e35'), u'floor': 0, u'altitude': 19.343869755277819, u'vaccuracy': 3.0, u'ts': 1456189018.000047, u'latitude': 37.391184275073357, u'sensed_speed': 9.0900001525878906, u'accuracy': 5.0, u'fmt_time': u'2016-02-22T16:56:58.000047-08:00', u'local_dt_minute': 56, 'metadata_write_ts': 1456189018.174159, u'longitude': -122.08619649533379, u'filter': u'distance', '_id': ObjectId('56cbcb4ceaedff78c763669e'), u'heading': 206.015625, u'local_dt_day': 22}) with index 221 
2016-08-20 22:00:06,636:INFO:Found trip end at 2016-02-22T16:56:58.000047-08:00
```

At this point, we compare this point with the previous point, and because they are within the filter, we treat it as a glom. Instead, we should start the new trip when we end the previous one.

**Comment by shankari** [comment]
Now testing with the trip end detection missing.
As expected, the test fails because we skip the trip whose trip end was detected.

on android

```
2016-08-21 07:54:07,180:DEBUG:140735159468032:Comparing 2016-08-09T17:54:54.529000-07:00 -> 2016-08-09T18:00:46-07:00 with 2016-08-09T17:54:54.529000-07:00 -> 2016-08-09T18:00:46-07:00
2016-08-21 07:54:07,181:DEBUG:140735159468032:Comparing 2016-08-09T18:04:16.449000-07:00 -> 2016-08-09T18:20:41-07:00 with 2016-08-09T18:04:16.449000-07:00 -> 2016-08-09T18:20:41-07:00
2016-08-21 07:54:07,181:DEBUG:140735159468032:Comparing 2016-08-10T11:07:05.684000-07:00 -> 2016-08-10T11:14:45.512000-07:00 with 2016-08-10T09:53:59.425000-07:00 -> 2016-08-10T10:02:11-07:00
2016-08-21 07:54:07,181:DEBUG:140735159468032:Comparing 2016-08-10T17:43:37.535000-07:00 -> 2016-08-10T18:00:18.899000-07:00 with 2016-08-10T11:07:05.684000-07:00 -> 2016-08-10T11:14:45.512000-07:00
2016-08-21 07:54:07,181:DEBUG:140735159468032:Comparing 2016-08-10T18:11:04.989000-07:00 -> 2016-08-10T18:13:49.871000-07:00 with 2016-08-10T17:43:37.535000-07:00 -> 2016-08-10T18:00:18.899000-07:00
2016-08-21 07:54:07,182:DEBUG:140735159468032:Comparing 2016-08-10T19:28:06.757000-07:00 -> 2016-08-10T19:48:43.490000-07:00 with 2016-08-10T18:11:04.989000-07:00 -> 2016-08-10T18:13:49.871000-07:00
F2016-08-21 07:54:07,182:DEBUG:140735159468032:Clearing related databases

======================================================================
FAIL: testAug10MultiSyncEndNotDetected (__main__.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 349, in testAug10MultiSyncEndNotDetected
    ad.AttrDict(ground_truth).data, time_fuzz=60, distance_fuzz=100)
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 92, in compare_approx_result
    self.assertEqual(len(result), len(expect))
AssertionError: 6 != 7

----------------------------------------------------------------------
```
and iOS

```
2016-08-21 08:08:16,808:DEBUG:140735159468032:Comparing 2016-02-22T13:06:06.142961-08:00 -> 2016-02-22T13:13:19.001847-08:00 with 2016-02-22T13:06:06.142961-08:00 -> 2016-02-22T13:13:19.001847-08:00
2016-08-21 08:08:16,808:DEBUG:140735159468032:Comparing 2016-02-22T15:33:18.550963-08:00 -> 2016-02-22T15:37:12.000136-08:00 with 2016-02-22T15:33:18.550963-08:00 -> 2016-02-22T15:37:12.000136-08:00
2016-08-21 08:08:16,809:DEBUG:140735159468032:Comparing 2016-02-22T15:49:43.999972-08:00 -> 2016-02-22T16:04:00.997765-08:00 with 2016-02-22T15:49:43.999972-08:00 -> 2016-02-22T16:04:00.997765-08:00
2016-08-21 08:08:16,809:DEBUG:140735159468032:Comparing 2016-02-22T19:41:42.085297-08:00 -> 2016-02-22T19:48:35.000033-08:00 with 2016-02-22T16:49:30.999990-08:00 -> 2016-02-22T16:56:58.000047-08:00
2016-08-21 08:08:16,809:DEBUG:140735159468032:Comparing 2016-02-22T19:58:50.000111-08:00 -> 2016-02-22T20:12:15.000095-08:00 with 2016-02-22T19:41:42.085297-08:00 -> 2016-02-22T19:48:35.000033-08:00
F2016-08-21 08:08:16,810:DEBUG:140735159468032:Clearing related databases

======================================================================
FAIL: testFeb22MultiSyncEndNotDetected (__main__.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 387, in testFeb22MultiSyncEndNotDetected
    ad.AttrDict(ground_truth).data, time_fuzz=60, distance_fuzz=100)
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 92, in compare_approx_result
    self.assertEqual(len(result), len(expect))
AssertionError: 5 != 6

----------------------------------------------------------------------
```

**Comment by shankari** [comment]
To fix this, I originally tried

```
            if self.has_trip_ended(prevPoint, currPoint, last10PointsDistances, last5MinsDistances, last5MinTimes):
                (ended_before_this, last_trip_end_point) = self.get_last_trip_end_point(filtered_points_df,
                                                                                       last10Points_df, last5MinsPoints_df)
                segmentation_points.append((curr_trip_start_point, last_trip_end_point))
                logging.info("Found trip end at %s" % last_trip_end_point.fmt_time)
                # We have processed everything up to the trip end by marking it as a completed trip
                self.last_ts_processed = last_trip_end_point.ts
```

with the last line being new.

but it doesn't work!!

Mismatch is caused by an extra trip here (18:20 -> 18:22)

```
2016-08-21 08:44:55,304:DEBUG:140735159468032:Comparing 2016-08-09T18:04:16.449000-07:00 -> 2016-08-09T18:20:41-07:00 with 2016-08-09T18:04:16.449000-07:00 -> 2016-08-09T18:20:41-07:00
2016-08-21 08:44:55,305:DEBUG:140735159468032:Comparing 2016-08-09T18:20:51-07:00 -> 2016-08-09T18:22:44-07:00 with 2016-08-10T09:53:59.425000-07:00 -> 2016-08-10T10:02:11-07:00
```

First run of TRIP_SEGMENTATION

```
2016-08-21 08:44:38,381:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, start_ts is None
...
2016-08-21 08:44:40,647:DEBUG:140735159468032:------------------------------2016-08-09T18:20:25-07:00------------------------------
2016-08-21 08:44:40,685:DEBUG:140735159468032:last5MinsDistances.max() = 218.536652166, last10PointsDistance.max() = 39.3911807103
2016-08-21 08:44:40,686:DEBUG:140735159468032:------------------------------2016-08-09T18:20:30-07:00------------------------------
2016-08-21 08:44:40,724:DEBUG:140735159468032:last5MinsDistances.max() = 218.398030207, last10PointsDistance.max() = 34.4317572066
2016-08-21 08:44:40,725:DEBUG:140735159468032:------------------------------2016-08-09T18:20:35-07:00------------------------------
2016-08-21 08:44:40,765:DEBUG:140735159468032:last5MinsDistances.max() = 220.016477435, last10PointsDistance.max() = 27.3530320749
2016-08-21 08:44:40,766:DEBUG:140735159468032:------------------------------2016-08-09T18:20:41-07:00------------------------------
2016-08-21 08:44:40,807:DEBUG:140735159468032:last5MinsDistances.max() = 165.487676485, last10PointsDistance.max() = 23.4193070859
2016-08-21 08:44:40,808:DEBUG:140735159468032:------------------------------2016-08-09T18:20:46-07:00------------------------------
2016-08-21 08:44:40,854:DEBUG:140735159468032:last5MinsDistances.max() = 165.487676485, last10PointsDistance.max() = 23.4193070859
2016-08-21 08:44:40,855:DEBUG:140735159468032:------------------------------2016-08-09T18:20:51-07:00------------------------------
2016-08-21 08:44:40,902:DEBUG:140735159468032:last5MinsDistances.max() = 165.487676485, last10PointsDistance.max() = 18.7859006459
2016-08-21 08:44:40,903:DEBUG:140735159468032:------------------------------2016-08-09T18:20:56-07:00------------------------------
2016-08-21 08:44:40,951:DEBUG:140735159468032:last5MinsDistances.max() = 165.487676485, last10PointsDistance.max() = 12.979505662
2016-08-21 08:44:40,951:DEBUG:140735159468032:------------------------------2016-08-09T18:21:01-07:00------------------------------
2016-08-21 08:44:40,996:DEBUG:140735159468032:last5MinsDistances.max() = 165.773671388, last10PointsDistance.max() = 7.76102902159
2016-08-21 08:44:40,996:DEBUG:140735159468032:------------------------------2016-08-09T18:21:50-07:00------------------------------
2016-08-21 08:44:41,033:DEBUG:140735159468032:last5MinsDistances.max() = 172.466451101, last10PointsDistance.max() = 27.0735532943
2016-08-21 08:44:41,034:DEBUG:140735159468032:------------------------------2016-08-09T18:22:15.081000-07:00------------------------------
2016-08-21 08:44:41,073:DEBUG:140735159468032:last5MinsDistances.max() = 202.915967329, last10PointsDistance.max() = 44.2315835096
2016-08-21 08:44:41,073:DEBUG:140735159468032:------------------------------2016-08-09T18:22:44-07:00------------------------------
2016-08-21 08:44:41,108:DEBUG:140735159468032:last5MinsDistances.max() = 171.072533117, last10PointsDistance.max() = 28.3372389934
...
2016-08-21 08:44:41,199:DEBUG:140735159468032:------------------------------2016-08-09T18:24:47.616000-07:00------------------------------
2016-08-21 08:44:41,219:DEBUG:140735159468032:last5MinsDistances.max() = 67.0090396361, last10PointsDistance.max() = 46.1957630142
2016-08-21 08:44:41,219:DEBUG:140735159468032:last5MinsPoints and last10PointsMedian found, last_trip_end_index = 101
2016-08-21 08:44:41,220:DEBUG:140735159468032:Appending last_trip_end_point AttrDict({u'local_dt_hour': 18, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 41, u'local_dt_year': 2016, u'local_dt_month': 8, u'local_dt_weekday': 1, u'elapsedRealtimeNanos': 343737513190784, u'loc': {u'type': u'Point', u'coordinates': [-122.0864294, 37.3904543]}, 'user_id': UUID('1d58b3a1-436f-4077-82d3-21d56898ae4b'), u'altitude': 0.899993896484375, u'ts': 1470792041.0, u'latitude': 37.390454300000002, u'sensed_speed': 0.0, u'accuracy': 5.0, u'fmt_time': u'2016-08-09T18:20:41-07:00', u'local_dt_minute': 20, 'metadata_write_ts': 1470792039.8710001, u'longitude': -122.0864294, u'filter': u'time', '_id': ObjectId('57aa88bdf311e474bfd90351'), u'heading': 349, u'local_dt_day': 9}) with index 101 
2016-08-21 08:44:41,220:INFO:140735159468032:Found trip end at 2016-08-09T18:20:41-07:00
...
2016-08-21 08:44:41,698:INFO:140735159468032:Returning last_ts_processed = 1470792041.0
2016-08-21 08:44:41,699:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, last_ts_processed = 2016-08-10T01:20:46
```

1470792041.0 = 2016-08-10T01:20:46 = 2016-08-09T18:20:41-07:00

```
2016-08-21 08:44:45,835:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2016-08-10T01:20:46

2016-08-21 08:44:45,923:DEBUG:140735159468032:------------------------------2016-08-09T18:20:51-07:00------------------------------
2016-08-21 08:44:45,923:DEBUG:140735159468032:Appending currPoint because the current start point is None
2016-08-21 08:44:45,924:DEBUG:140735159468032:Setting new trip start point AttrDict({u'local_dt_hour': 18, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 51, u'local_dt_year': 2016, u'local_dt_month': 8, u'local_dt_weekday': 1, u'elapsedRealtimeNanos': 343747562324085, u'loc': {u'type': u'Point', u'coordinates': [-122.0864294, 37.3904543]}, 'user_id': UUID('1d58b3a1-436f-4077-82d3-21d56898ae4b'), u'altitude': 0.899993896484375, u'ts': 1470792051.0, u'latitude': 37.3904543, u'sensed_speed': 0.0, u'accuracy': 5.0, u'fmt_time': u'2016-08-09T18:20:51-07:00', u'local_dt_minute': 20, 'metadata_write_ts': 1470792050.42, 'idx': 0, u'longitude': -122.0864294, u'filter': u'time', '_id': ObjectId('57aa88bdf311e474bfd90355'), u'heading': 349, u'local_dt_day': 9}) with idx 0
```

Clearly, the problem was that we were setting the last_ts_processed to the end of the trip, when we should have set it to the last point processed.

A quick check on why we restart with 2016-08-09T18:20:51-07:00 instead of the
point after the trip end (2016-08-09T18:20:46-07:00).

The segmenter returns `2016-08-09T18:20:41-07:00`.

```
2016-08-21 08:44:41,220:INFO:140735159468032:Found trip end at 2016-08-09T18:20:41-07:00
...
2016-08-21 08:44:41,698:INFO:140735159468032:Returning last_ts_processed = 1470792041.0
```

We add in a 5 sec fuzz factor, so we actually set the last_ts_processed to
*2016-08-10T01:20:46*, which is the timestamp of the next point

```
2016-08-21 08:44:40,766:DEBUG:140735159468032:------------------------------2016-08-09T18:20:41-07:00------------------------------
2016-08-21 08:44:40,807:DEBUG:140735159468032:last5MinsDistances.max() = 165.487676485, last10PointsDistance.max() = 23.4193070859
2016-08-21 08:44:40,808:DEBUG:140735159468032:------------------------------2016-08-09T18:20:46-07:00------------------------------
...
2016-08-21 08:44:41,699:INFO:140735159468032:For stage PipelineStages.TRIP_SEGMENTATION, last_ts_processed = 2016-08-10T01:20:46
```

But when we query, we don't query by data.ts, but by metadata.write_ts. And
although the next point was generated at `18:20:46`, it was written a teeny bit before(??).

```
esta.TimeSeries.get_time_series(curr_id).get_data_df("background/filtered_location", estt.TimeQuery("data.ts", 1470792046.0, 1471794280.835577)).head()[["fmt_time", "ts", "metadata_write_ts"]]

    fmt_time    ts  metadata_write_ts
0   2016-08-09T18:20:46-07:00   1470792046.000  1470792044.842
1   2016-08-09T18:20:51-07:00   1470792051.000  1470792050.420
2   2016-08-09T18:20:56-07:00   1470792056.000  1470792054.991
3   2016-08-09T18:21:01-07:00   1470792061.000  1470792075.239
4   2016-08-09T18:21:50-07:00   1470792110.000  1470792128.566
```
