### ISSUE TITLE
Switching between android and ios in the middle of a trip causes a crash

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#422]
Got this error while running against real data.

````
2016-09-23 17:50:46,043:ERROR:140342407587648:Found error cannot set a row with mismatched columns while processing trip Entry()
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 101, in save_cleaned_segments_for_timeline
    filtered_trip = get_filtered_trip(ts, trip)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 166, in get_filtered_trip
    section_map[section.get_id()] = get_filtered_section(filtered_trip_entry, section)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 259, in get_filtered_section
    with_speeds_df = get_filtered_points(section, filtered_section_data)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 359, in get_filtered_points
    filtered_loc_df = _add_start_point(filtered_loc_df, raw_start_place, ts)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 579, in _add_start_point
    return _insert_new_entry(-1, filtered_loc_df, new_first_point)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 651, in _insert_new_entry
    loc_df.loc[index] = new_point_row
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 128, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py", line 363, in _setitem_with_indexer
    raise ValueError("cannot set a row with "
ValueError: cannot set a row with mismatched columns
```

It turned out to be due to a platform mismatch.

```
2016-09-23 17:50:46,037:DEBUG:140342407587648:After copy, new data = Location({u'loc': {}, u'altitude': ..., u'longitude': ..., u'filter': u'time', u'latitude': ..., u'elapsedRealtimeNanos': 12286001205102L, u'heading': 30, u'sensed_speed': 1.5476091, u'accuracy': 48})
2016-09-23 17:50:46,041:DEBUG:140342407587648:Missing cols = set([u'vaccuracy', u'floor'])
2016-09-23 17:50:46,042:DEBUG:140342407587648:Missing cols = set([])
2016-09-23 17:50:46,042:DEBUG:140342407587648:Missing cols switched around = set([u'elapsedRealtimeNanos'])
```

The location for the place was android

```
2016-09-23 17:50:46,008:DEBUG:140342407587648:get_entry_at_ts query = {'metadata.key': 'background/filtered_location', 'user_id': UUID('2c3996d1-49b1-4dce-82f8-d0cda85d3475'), 'data.ts': 1472079336.999}
2016-09-23 17:50:46,009:DEBUG:140342407587648:Raw place is 57e56aed88f6637ac4b2ef2b and corresponding location is 57be2e660a3eb8b13006289a
{u'_id': ObjectId('57be2e660a3eb8b13006289a'),
 u'data': {u'accuracy': 48,
  u'altitude': 59.06366897796765,
  u'elapsedRealtimeNanos': 12286001205102L,
  u'filter': u'time',
  u'fmt_time': u'2016-08-25T10:55:36.999000+12:00',
  u'heading': 30,
  u'latitude': -36.88122,
  u'ts': 1472079336.999},
 u'metadata': {u'key': u'background/filtered_location',
  u'platform': u'android',
  u'read_ts': 0,
  u'write_fmt_time': u'2016-08-25T10:55:36.625000+12:00',
  u'write_ts': 1472079336.625},
```

And all the points in the trip were ios

```
2016-09-23 17:50:45,968:DEBUG:140342407587648:curr_query = {'$or': [{'metadata.key': 'background/filtered_location'}], 'user_id': UUID('2c3996d1-49b1-4dce-82f8-d0cda85d3475'), 'data.ts': {'$lte': 1472101112.098742, '$gte': 1472100447.431967}}, sort_key = data.ts

In [391]: for e in edb.get_timeseries_db().find({'$or': [{'metadata.key': 'background/filtered_location'}], 'user_id': UUID('2c3996d1-49b1-4dce-82f8-d0cda85d3475'), 'data.ts': {'$lte': 1472101112.098742, '$gte': 1472100447.431967}}):
    print e["metadata"]["platform"], e["metadata"]["write_fmt_time"]
   .....:     
ios 2016-08-25T16:58:32.147516+12:00
ios 2016-08-25T16:58:10.120632+12:00
ios 2016-08-25T16:57:50.164614+12:00
ios 2016-08-25T16:57:32.197016+12:00
ios 2016-08-25T16:57:15.402773+12:00
ios 2016-08-25T16:56:57.220088+12:00
ios 2016-08-25T16:56:26.360213+12:00
ios 2016-08-25T16:56:00.390638+12:00
ios 2016-08-25T16:55:29.958307+12:00
ios 2016-08-25T16:55:01.431602+12:00
ios 2016-08-25T16:54:37.214264+12:00
ios 2016-08-25T16:54:05.750592+12:00
ios 2016-08-25T16:53:39.207870+12:00
ios 2016-08-25T16:53:10.199526+12:00
ios 2016-08-25T16:52:41.215544+12:00
ios 2016-08-25T16:52:13.440924+12:00
ios 2016-08-25T16:51:48.137352+12:00
ios 2016-08-25T16:51:19.335443+12:00
ios 2016-08-25T16:50:51.188870+12:00
ios 2016-08-25T16:50:22.117228+12:00
ios 2016-08-25T16:49:57.408601+12:00
ios 2016-08-25T16:49:32.212503+12:00
ios 2016-08-25T16:49:08.420674+12:00
ios 2016-08-25T16:48:45.314179+12:00
ios 2016-08-25T16:48:21.158052+12:00
ios 2016-08-25T16:47:54.283582+12:00
ios 2016-08-25T16:47:28.893270+12:00
```

It looks like the user is running both android and ios at the same time with the same email ID. Sent an email clarifying that it is not a valid use case. But we still need to not crash in this case, and be somewhat graceful with it since people can switch from ios to android, although maybe not at the same time... :)

**Comment by shankari** [comment]
Does not appear to be reproducible when I pull data. Seeing why...

**Comment by shankari** [comment]
On production:

```
2016-09-23 16:55:43,456:DEBUG:140342407587648:------------------------------2016-08-25T10:55:36.999000+12:00------------------------------
2016-09-23 16:55:43,556:DEBUG:140342407587648:------------------------------2016-08-25T10:56:00.999000+12:00------------------------------
2016-09-23 16:55:43,651:DEBUG:140342407587648:------------------------------2016-08-25T10:56:16.660000+12:00------------------------------
2016-09-23 16:55:43,743:DEBUG:140342407587648:------------------------------2016-08-25T10:56:33.999000+12:00------------------------------
2016-09-23 16:55:43,830:DEBUG:140342407587648:------------------------------2016-08-25T15:45:17.241758+12:00------------------------------
2016-09-23 16:55:43,848:DEBUG:140342407587648:prev_point.ts = 1472079394.0, curr_point.ts = 1472096717.24, time gap = 17323.242758 (vs 300), distance_gap = 33365.4684468 (vs 100), speed_gap = 1.92605212043 (vs 0.333333333333) continuing trip
2016-09-23 16:55:43,850:DEBUG:140342407587648:------------------------------2016-08-25T16:47:27.431967+12:00------------------------------
2016-09-23 16:55:43,868:DEBUG:140342407587648:prev_point.ts = 1472096717.24, curr_point.ts = 1472100447.43, threshold = 300, large gap = 3730.19020891, ending trip
2016-09-23 16:55:43,872:INFO:140342407587648:Found trip end at 2016-08-25T10:55:36.999000+12:00
```

On re-run:

```
2016-09-25 19:27:53,531:DEBUG:140735159468032:------------------------------2016-08-25T10:55:36.999000+12:00------------------------------
2016-09-25 19:27:53,561:DEBUG:140735159468032:------------------------------2016-08-25T10:56:00.999000+12:00------------------------------
2016-09-25 19:27:53,590:DEBUG:140735159468032:------------------------------2016-08-25T10:56:16.660000+12:00------------------------------
2016-09-25 19:27:53,619:DEBUG:140735159468032:------------------------------2016-08-25T10:56:33.999000+12:00------------------------------
2016-09-25 19:27:53,669:DEBUG:140735159468032:curr_query = {'$or': [{'metadata.key': 'statemachine/transition'}], 'metadata.write_ts': {'$lte': 1472103694.8345261, '$gte': 1472096717.2417581}, 'user_id': UUID('e191d777-9eae-47b6-879e-74032ce835e6')}, sort_key = metadata.write_ts
2016-09-25 19:27:53,683:DEBUG:140735159468032:------------------------------2016-08-25T15:45:17.241758+12:00------------------------------

2016-09-25 19:27:53,683:DEBUG:140735159468032:Setting new trip start point AttrDict({u'local_dt_hour': 15, u'local_dt_timezone': u'Pacific/Auckland', u'local_dt_second': 17, u'local_dt_year': 2016, u'local_dt_month': 8, u'local_dt_weekday': 3, u'loc': {u'type': u'Point', u'coordinates': [174.8991473113884, -37.17895796525961]}, 'user_id': UUID('e191d777-9eae-47b6-879e-74032ce835e6'), u'floor': 0, u'altitude': 44, u'vaccuracy': 4, u'ts': 1472096717.241758, u'latitude': -37.17895796525961, u'sensed_speed': 0.0, u'accuracy': 5, u'fmt_time': u'2016-08-25T15:45:17.241758+12:00', u'local_dt_minute': 45, 'metadata_write_ts': 1472100448.857791, 'idx': 0, u'longitude': 174.8991473113884, u'filter': u'distance', '_id': ObjectId('57e87ab5f6858f6a2864118a'), u'heading': 317.4609375, u'local_dt_day': 25}) with idx 0
```

That's because we split into time and distance filters.

```
2016-09-25 19:27:19,381:DEBUG:140735159468032:Filters in the dataframe = [u'time' u'distance']
2016-09-25 19:27:19,383:DEBUG:140735159468032:for filter time, startTs = 1472067269 and endTs = 1472079393
2016-09-25 19:27:53,651:DEBUG:140735159468032:for filter distance, startTs = 1472096717 and endTs = 1472103694

Time is from 2016-08-25T07:34:29+12:00 to 2016-08-25T10:56:33+12:00.
Distance is from 2016-08-25T15:45:17+12:00 to 2016-08-25T17:41:34+12:00
```

We need to have more android points to hit the error. Although, shouldn't we try to use pending time filter points with the dist filter? Wonder if that it over-optimizing though.
I can think of a way to do it, namely by picking the time range from the last segmentation ts of the first filter instead of the last timestamp. But I'd have to think through the implications of using the wrong filter on the data.

Also, the current solution only works if there is a single switch from one filter to another, so is not ideal for dealing with pipeline re-runs. I did notice that the distance and time filter algorithms seems to be converging, so it seems like it would be useful to see if we can merge them into a single algorithm which would then remove the need for such filtering.

That's something to investigate after we are done with bic2cal.

**Comment by shankari** [comment]
After pulling data from the next day with android points (`2016-08-28`), I am able to reproduce.
