### ISSUE TITLE
AssertionFailure while converting to geojson

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#455]
There have been no recent changes to trip segmentation or geojson conversion except for adding the incidents. Unsure why this is showing up just now.

```
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 260, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 219, in trip_to_geojson
    section_gj = section_to_geojson(section, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 123, in section_to_geojson
    assert(False)
AssertionError
2016-12-04 22:11:16,100:ERROR:140419539662656:Storing views to cache failed for user 365fc61a-033c-49ec-8f47-6fc5fbc36151
```

and 

```
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 260, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 219, in trip_to_geojson
    section_gj = section_to_geojson(section, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 123, in section_to_geojson
    assert(False)
AssertionError
2016-12-04 22:18:30,742:ERROR:140419539662656:Storing views to cache failed for user 95e70727-a04e-3e33-b7fe-34ab19194f8b
```

Assertion is at

```
            logging.info("section_location_array[-1].data.loc %s != section.data.end_loc %s even after df.ts fix, filling gap" % \
                    (section_location_entries[-1].data.loc, section.data.end_loc))
            assert(False)
            last_loc_doc = ts.get_entry_at_ts("background/filtered_location", "data.ts", section.data.end_ts)
            if last_loc_doc is None:
                logging.warning("can't find entry to patch gap, leaving gap")
            else:
                last_loc_entry = ecwe.Entry(last_loc_doc)
                logging.debug("Adding new entry %s to fill the end point gap between %s and %s"
                   % (last_loc_entry.data.loc, section_location_entries[-1].data.loc,
                        section.data.end_loc))
                section_location_entries.append(last_loc_entry)
```

**Comment by shankari** [comment]
First failure was between:

```
2016-11-24T01:08:23.602024+00:00**********UUID be47f46a-ce3a-4aNo user defined overrides 
for c2b47543-2ef6-42aa-b85c-efb7456c884f, early return
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_featur
e_converter.py", line 224, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_featur
e_converter.py", line 187, in trip_to_geojson
    section_gj = section_to_geojson(section, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 120, in section_to_geojson
    assert(False)
AssertionError
Storing views to cache failed for user 4a1202a9-f770-4521-b607-35c7bb8683d4
2016-11-24T01:07:51.679015+00:00**********UUID c2b47543-2ef6-42aa-b85c-efb7456c884f: smoothing sections**********
```

So definitely not part of the most recent change.

**Comment by shankari** [comment]
This first started for user `4a1202a9-f770-4521-b607-35c7bb8683d4`.
Then for both `4a1202a9-f770-4521-b607-35c7bb8683d4` and `365fc61a-033c-49ec-8f47-6fc5fbc36151`
And now for `365fc61a-033c-49ec-8f47-6fc5fbc36151` and `95e70727-a04e-3e33-b7fe-34ab19194f8b`.

Did `4a1202a9-f770-4521-b607-35c7bb8683d4` auto-resolve? How?

**Comment by shankari** [comment]
Yup, `4a1202a9-f770-4521-b607-35c7bb8683d4` is running fine now. 

```
2016-12-04T22:29:35.441108+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: movi
ng to long term**********
2016-12-04T22:30:24.748444+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: filt
er accuracy if needed**********
2016-12-04T22:30:24.760638+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: segm
enting into trips**********
2016-12-04T22:30:27.011344+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: segm
enting into sections**********
2016-12-04T22:30:27.564455+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: smoo
thing sections**********
2016-12-04T22:30:28.172851+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: clea
ning and resampling timeline**********
2016-12-04T22:30:30.080109+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: checking active mode trips to autocheck habits**********
2016-12-04T22:30:30.084730+00:00**********UUID 4a1202a9-f770-4521-b607-35c7bb8683d4: storing views to cache**********
```

**Comment by shankari** [comment]
Failures for most recent user started around 

```
2016-12-02T22:12:35.442579+00:00**********UUID 66e1f6b5-a7f5-40b4-b3b4-bb50aae9ffdf: segm
enting into triNo user defined overrides for 66e1f6b5-a7f5-40b4-b3b4-bb50aae9ffdf, early 
return
Storing views to cache failed for user 95e70727-a04e-3e33-b7fe-34ab19194f8b
2016-12-02T22:13:04.942692+00:00**********UUID 66e1f6b5-a7f5-40b4-b3b4-bb50aae9ffdf: segmenting into sections**********
```

Let's try to find the relevant logs...

**Comment by shankari** [comment]
Apparently, this was in process 0. Dec 2nd is in one of these logs.

```
-rw-rw-r-- 1 ubuntu ubuntu 67108838 Dec  3 09:00 intake_0.log.gz.2
-rw-rw-r-- 1 ubuntu ubuntu 67108824 Dec  2 18:33 intake_0.log.gz.3
-rw-rw-r-- 1 ubuntu ubuntu 67106380 Dec  1 21:15 intake_0.log.gz.4
```

**Comment by shankari** [comment]
This is the mismatch

```
2016-12-02 22:25:22,083:INFO:139892304086848:section_location_array[-1].data.loc {"coordinates": [-122.144875784569, 37.43146008958254], "type": "Point"} != section.data.end_loc {"coordinates": [-122.1448342718504, 37.43143061570762], "type": "Point"} even after df.ts fix, filling gap
```

This is the query for the recreated locations.

```
2016-12-02 22:25:22,070:DEBUG:139892304086848:curr_query = {'$or': [{'metadata.key': 'analysis/recreated_location'}], 'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b'), 'data.ts': {'$lte': 1480703009.021435, '$gte': 1480702558.829766}}, sort_key = data.ts
```

And the trip is 

```
2016-12-02 22:25:22 084:ERROR:139892304086848:Found error  while processing trip Entry({u'data': {u'distance': 79689.54093939689
 u'end_place': ObjectId('5841f4bc88f66320b72a89e6')
 u'raw_trip': ObjectId('5841f4a888f66320b72a8886')
 u'start_loc': {u'type': u'Point' u'coordinates': [-122.0864943881725 37.39106709606703]}
 u'end_ts': 1480710596.608059
 u'start_ts': 1480701888.1039107
 u'start_fmt_time': u'2016-12-02T10:04:48.103911-08:00'
 u'end_loc': {u'type': u'Point' u'coordinates': [-122.2584625410114 37.87532196131724]}
 u'source': u'DwellSegmentationDistFilter'
 u'start_place': ObjectId('583fcc6088f663746954af43')
 u'end_fmt_time': u'2016-12-02T12:29:56.608059-08:00'
 u'duration': 8708.504148244858
 u'_id': ObjectId('5841f4b088f66320b72a88b3')
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')
 u'metadata': {u'write_fmt_time': u'2016-12-02T14:24:48.840586-08:00'
 u'write_ts': 1480717488.840586
 u'time_zone': u'America/Los_Angeles'
 u'platform': u'server'
 u'key': u'analysis/cleaned_trip'}})
```

Corresponding raw trip is

```
2016-12-02 22:25:00,284:DEBUG:139892304086848:Found mapping 5841f4a888f66320b72a8886 -> 5841f4b088f66320b72a88b3, added links
```

Here's where it was cleaned

```
2016-12-02 22:24:48,716:DEBUG:139892304086848:About to execute query {'data.trip_id': ObjectId('5841f4a888f66320b72a8886'), 'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b'), 'metadata.key': 'segmentation/raw_section'} with sort_key data.start_ts
```

There are multiple matching sections

```
2016-12-02 22:24:48,838:DEBUG:139892304086848:trips_or_sections = [ObjectId('5841f4ab88f66320b72a8889'), ObjectId('5841f4ab88f66320b72a888a'), ObjectId('5841f4ab88f66320b72a888c'), ObjectId('5841f4ab88f66320b72a888e'), ObjectId('5841f4ab88f66320b72a8890'), ObjectId('5841f4ab88f66320b72a8892'), ObjectId('5841f4ab88f66320b72a8894'), ObjectId('5841f4ab88f66320b72a8896'), ObjectId('5841f4ab88f66320b72a8898'), ObjectId('5841f4ac88f66320b72a889a'), ObjectId('5841f4ac88f66320b72a889c'), ObjectId('5841f4ac88f66320b72a889e'), ObjectId('5841f4ac88f66320b72a88a0'), ObjectId('5841f4ac88f66320b72a88a2')] 
```

This appears to be the relevant section.

```
2016-12-02 22:24:49
879:DEBUG:139892304086848:Getting filtered points for section Entry({u'data': {u'sensed_mode': 0
 u'start_loc': {u'type': u'Point' u'coordinates': [-122.1007768149877 37.40452883274393]}
 u'end_ts': 1480703009.021435
 u'start_ts': 1480702558.829766
 u'start_fmt_time': u'2016-12-02T10:15:58.829766-08:00'
 u'end_loc': {u'type': u'Point' u'coordinates': [-122.1448342718504 37.43143061570762]}
 u'source': u'SmoothedHighConfidenceMotion'
 u'end_fmt_time': u'2016-12-02T10:23:29.021435-08:00'
 u'duration': 450.19166898727417
 u'start_stop': ObjectId('5841f4ab88f66320b72a888f')
 u'end_stop': ObjectId('5841f4ab88f66320b72a8891')
 u'trip_id': ObjectId('5841f4a888f66320b72a8886')
 u'_id': ObjectId('5841f4ab88f66320b72a888e')
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')
 u'metadata': {u'write_fmt_time': u'2016-12-02T14:24:43.441274-08:00'
 u'write_ts': 1480717483.441274
 u'time_zone': u'America/Los_Angeles'
 u'platform': u'server'
 u'key': u'segmentation/raw_section'}})

2016-12-02 22:24:49,880:DEBUG:139892304086848:Saving entries into cleaned section Cleanedsection({u'source': u'SmoothedHighConfidenceMotion', 'trip_id': ObjectId('5841f4b088f66320b72a88b3')})

2016-12-02 22:24:49,882:DEBUG:139892304086848:curr_query = {'$or': [{'metadata.key': 'background/filtered_location'}], 'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b'), 'data.ts': {'$lte': 1480703009.021435, '$gte': 1480702558.829766}}, sort_key = data.ts
2016-12-02 22:24:49,915:DEBUG:139892304086848:deleting 1 points from section points
2016-12-02 22:24:49,927:DEBUG:139892304086848:Found 31 results

2016-12-02 22:24:49,944:DEBUG:139892304086848:Setting section start and end values of Cleanedsection({u'source': u'SmoothedHighConfidenceMotion', 'trip_id': ObjectId('5841f4b088f66320b72a88b3')}) to last point accuracy                                                           165
altitude                                                       14.2229
filter                                                        distance
floor                                                                0
fmt_time                              2016-12-02T10:23:29.021435-08:00
heading                                                             -1
latitude                                                       37.4314
loc                  {u'type': u'Point', u'coordinates': [-122.1448...
local_dt_minute                                                     23
local_dt_second                                                     29
longitude                                                     -122.145
metadata_write_ts                                           1.4807e+09
sensed_speed                                                        -1
ts                                                          1.4807e+09
user_id                           95e70727-a04e-3e33-b7fe-34ab19194f8b
vaccuracy                                                           10
```

**Comment by shankari** [comment]
It looks like the section's end loc is the end loc of the raw_section.

```
2016-12-02 22:25:22,083:INFO:139892304086848:section_location_array[-1].data.loc {"coordinates": [-122.144875784569, 37.43146008958254], "type": "Point"} != section.data.end_loc {"coordinates": [-122.1448342718504, 37.43143061570762], "type": "Point"} even after df.ts fix, filling gap
```

```
2016-12-02 22:24:49
879:DEBUG:139892304086848:Getting filtered points for section Entry({u'data': {u'sensed_mode': 0
 u'start_loc': {u'type': u'Point' u'coordinates': [-122.1007768149877 37.40452883274393]}
 u'end_ts': 1480703009.021435
 u'start_ts': 1480702558.829766
 u'start_fmt_time': u'2016-12-02T10:15:58.829766-08:00'
 u'end_loc': {u'type': u'Point' u'coordinates': [-122.1448342718504 37.43143061570762]}
 u'source': u'SmoothedHighConfidenceMotion'
 u'end_fmt_time': u'2016-12-02T10:23:29.021435-08:00'
 u'duration': 450.19166898727417
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')
 u'key': u'segmentation/raw_section'}})
```

But the set of points has a different value (`-122.144875784569,
37.43146008958254`). Could it be that the interpolation from the next section
set the start of the next cleaned section to be before the end of this one?

Let's look for that point in the logs.

**Comment by shankari** [comment]
It looks like the section's end loc is the end loc of the raw_section.

```
2016-12-02 22:25:22,083:INFO:139892304086848:section_location_array[-1].data.loc {"coordinates": [-122.144875784569, 37.43146008958254], "type": "Point"} != section.data.end_loc {"coordinates": [-122.1448342718504, 37.43143061570762], "type": "Point"} even after df.ts fix, filling gap
```

```
2016-12-02 22:24:49
879:DEBUG:139892304086848:Getting filtered points for section Entry({u'data': {u'sensed_mode': 0
 u'start_loc': {u'type': u'Point' u'coordinates': [-122.1007768149877 37.40452883274393]}
 u'end_ts': 1480703009.021435
 u'start_ts': 1480702558.829766
 u'start_fmt_time': u'2016-12-02T10:15:58.829766-08:00'
 u'end_loc': {u'type': u'Point' u'coordinates': [-122.1448342718504 37.43143061570762]}
 u'source': u'SmoothedHighConfidenceMotion'
 u'end_fmt_time': u'2016-12-02T10:23:29.021435-08:00'
 u'duration': 450.19166898727417
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')
 u'key': u'segmentation/raw_section'}})
```

But the set of points has a different value (`-122.144875784569,
37.43146008958254`). Could it be that the interpolation from the next section
set the start of the next cleaned section to be before the end of this one?

Let's look for that point in the logs.

Only match is in the trip segmentation, and this point (10:23:42) is after the the point for the section end (10:23:29). 

```
2016-12-02 22:24:37,816:DEBUG:139892304086848:------------------------------2016-12-02T10:23:42.029405-08:00------------------------------
2016-12-02 22:24:37,819:DEBUG:139892304086848:lastPoint = AttrDict({u'local_dt_hour': 10, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_second': 29, u'local_dt_year': 2016, u'local_dt_month': 12, u'local_dt_weekday': 4, u'loc': {u'type': u'Point', u'coordinates': [-122.144875784569, 37.43146008958254]}, 'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b'), u'floor': 0, u'altitude': 14.160969734191889, u'vaccuracy': 10.0, u'ts': 1480703009.021435, u'latitude': 37.431460089582536, u'sensed_speed': -1.0, u'accuracy': 165.0, u'fmt_time': u'2016-12-02T10:23:29.021435-08:00', u'local_dt_minute': 23, 'metadata_write_ts': 1480703010.5249281, u'longitude': -122.144875784569, u'filter': u'distance', '_id': ObjectId('5841e168cb17471ac0f425c2'), u'heading': -1.0, u'local_dt_day': 2}), time difference = 13.0079700947 dist difference 246.570264082
```

And if this showed up for the segmentation, it is not even a recreated
location. Let's see what range we have queried for the recreated locations.

The range is consistent with the section start and end.

```
2016-12-02 22:25:22,070:DEBUG:139892304086848:curr_query = {'$or': [{'metadata.key': 'analysis/recreated_location'}], 'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b'), 'data.ts': {'$lte': 1480703009.021435, '$gte': 1480702558.829766}}, sort_key = data.ts
```

```
 u'start_loc': {u'type': u'Point' u'coordinates': [-122.1007768149877 37.40452883274393]}
 u'end_ts': 1480703009.021435
 u'start_ts': 1480702558.829766
```

And the first point matches.

```
2016-12-02 22:25:22
082:DEBUG:139892304086848:first element in section_location_array = Entry({u'data': {u'loc': {u'type': u'Point'
 u'coordinates': [-122.1007768149877
 37.40452883274393]}
 u'idx': 0
 u'fmt_time': u'2016-12-02T10:15:58.829766-08:00'
 u'altitude': 26.88357925415039
 u'ts': 1480702558.829766
 u'longitude': -122.1007768149877
 u'heading': 0.0
 u'mode': 0
 u'latitude': 37.40452883274393
 u'speed': 0.0
 u'section': ObjectId('5841f4b288f66320b72a88c7')
 u'distance': 0.0}
 u'_id': ObjectId('5841f4b288f66320b72a88c8')
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')
 u'key': u'analysis/recreated_location'}})
```

**Comment by shankari** [comment]
I can confirm that the last retrieved point is a `recreated_location` with the timestamp of the last point (`1480703009.021435`) but a different location (`-122.144875784569, 37.43146008958254` instead of `-122.1448342718504 37.43143061570762`)

```
{u'_id': ObjectId('5841f4b288f66320b72a88d8'),
 u'data': {u'altitude': 14.16096973419189,
  u'distance': 14.751026868614096,
  u'fmt_time': u'2016-12-02T10:23:29.021435-08:00',
  u'heading': -48.19974229357621,
  u'idx': 16,
  u'latitude': 37.43146008958254,
  u'loc': {u'coordinates': [-122.144875784569, 37.43146008958254], u'type': u'Point'},
  u'longitude': -122.144875784569,
  u'mode': 0,
  u'section': ObjectId('5841f4b288f66320b72a88c7'),
  u'speed': 76.9609475084966,
  u'ts': 1480703009.021435},
 u'metadata': {u'key': u'analysis/recreated_location',
 u'user_id': UUID('95e70727-a04e-3e33-b7fe-34ab19194f8b')}
```

**Comment by shankari** [comment]
It looks like when we recreate the locations, the interpolation function doesn't always return the start and end locations for the start and end times. I guess that is possible although I would assume that the function would try to make at least the start and end points be fixed points.

**Comment by shankari** [comment]
Looking at the resampling more carefully.

```
2016-12-02 22:24:49,958:DEBUG:139892304086848:Resampling entry list                            fmt_time            ts   longitude   latitude
0  2016-12-02T10:15:58.829766-08:00  1.480703e+09 -122.100777  37.404529
1  2016-12-02T10:15:59.986326-08:00  1.480703e+09 -122.100777  37.404529
2  2016-12-02T10:15:59.993864-08:00  1.480703e+09 -122.100841  37.404553
3  2016-12-02T10:15:59.993864-08:00  1.480703e+09 -122.100819  37.404545
4  2016-12-02T10:16:06.431930-08:00  1.480703e+09 -122.102120  37.405023 of size 30


2016-12-02 22:24:49,963:DEBUG:139892304086848:tz_ranges = [{'timezone': u'America/Los_Angeles', 'end_ts': 1480703009.021435, 'start_ts': 1480702558.829766}]
2016-12-02 22:24:49,970:DEBUG:139892304086848:After resampling, using 17 points from 1480702558.83 -> 1480703009.02
```

**Comment by shankari** [comment]
I am going to comment out the assert for now. In the next release, I will add a check to either reset the end_loc of the section to match the last point, or to reset the last point to match the end_loc

**Comment by shankari** [comment]
Commented out the assert

```
            logging.info("section_location_array[-1].data.loc %s != section.data.end_loc %s even after df.ts fix, filling gap" % \
                    (section_location_entries[-1].data.loc, section.data.end_loc))
            # assert(False)
            last_loc_doc = ts.get_entry_at_ts("background/filtered_location", "data.ts", section.data.end_ts)
```
