### ISSUE TITLE
local token decoding using the oauthclient2 library fails

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#520]
I wonder if the token format has changed.

The stacktrace is

```
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/net/api/bottle.py", line 850, in _handl
e
    return route.call(**args)
  File "/mnt/e-mission/e-mission-server/emission/net/api/bottle.py", line 1721, in wrapp
er
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 365, in putIntoCache
    user_uuid=getUUID(request)
  File "emission/net/api/cfc_webapp.py", line 778, in getUUID
    retUUID = getUUIDFromToken(userToken)
  File "emission/net/api/cfc_webapp.py", line 740, in getUUIDFromToken
    userEmail = verifyUserToken(token)
  File "emission/net/api/cfc_webapp.py", line 707, in verifyUserToken
    tokenFields = oauth2client.client.verify_id_token(token,client_key)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 13
5, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/oauth2client/client.py", line
1675, in verify_id_token
    resp, content = http.request(cert_uri)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/httplib2/__init__.py", line 15
60, in request
    entry_disposition = _entry_disposition(info, headers)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/httplib2/__init__.py", line 36
4, in _entry_disposition
    date = calendar.timegm(email.Utils.parsedate_tz(response_headers['date']))
  File "/home/ubuntu/anaconda/lib/python2.7/calendar.py", line 612, in timegm
    year, month, day, hour, minute, second = tuple[:6]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Appears to happen only on iOS; android is fine.
This was reported today morning by Randy Katz.

I haven't touched either the app or the server for at least the past week (I've been writing and dealing with students, etc), so this can't be related to any change that I made. It must be a change in google's format for iOS tokens.

**Comment by shankari** [comment]
I was able to reproduce this by installing a new version from the store. It failed even on login because the tokens were not validated.

**Comment by shankari** [comment]
Worked around by disabling all local validation and using the google token authentication API instead (e.g. the fallback at https://github.com/e-mission/e-mission-server/blob/master/emission/net/api/cfc_webapp.py#L726)

Everything works now.

Note that this is more evidence that the tokens are valid, and that the python validation library is the one that is broken. But there have been no notices about this...

**Comment by shankari** [comment]
In particular, we get try to get and cache google certificates so that we can verify locally.
But the call to get the cert no longer returns the correct headers.
Need to look up the new google identity solution and see what libraries they recommend.

```
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/oauth2client/client.py", line
1675, in verify_id_token
    resp, content = http.request(cert_uri)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/httplib2/__init__.py", line 15
60, in request
    entry_disposition = _entry_disposition(info, headers)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/httplib2/__init__.py", line 36
4, in _entry_disposition
    date = calendar.timegm(email.Utils.parsedate_tz(response_headers['date']))
  File "/home/ubuntu/anaconda/lib/python2.7/calendar.py", line 612, in timegm
    year, month, day, hour, minute, second = tuple[:6]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by shankari** [comment]
workaround in https://github.com/e-mission/e-mission-server/issues/520#issuecomment-331060536 works for iOS but broke android. This is because we are still using the old client id on android, but we hadn't modified the fallback checking to use it.

with this diff, works on both android and iOS.

```
-                    r = requests.get(constructedURL)
-                    tokenFields = json.loads(r.content)
-                    in_client_key = tokenFields['audience']
-                    if (in_client_key != client_key):
-                        if (in_client_key != ios_client_key and
-                            in_client_key != ios_client_key_new):
-                            abort(401, "Invalid client key %s" % in_client_key)
+    r = requests.get(constructedURL)
+    tokenFields = json.loads(r.content)
+    in_client_key = tokenFields['audience']
+    logging.debug("in_client_key = %s" % in_client_key)
+    if (in_client_key != client_key_old and
+        in_client_key != client_key):
+       if (in_client_key != ios_client_key and
+           in_client_key != ios_client_key_new):
+           abort(401, "Invalid client key %s" % in_client_key)
```

**Comment by shankari** [comment]
Aha! oauth2client is deprecated.
https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html
New library is google-auth
https://google-auth.readthedocs.io/en/latest/

Code example using google-auth is at
https://developers.google.com/identity/sign-in/android/backend-auth
