### ISSUE TITLE
registering for habitica is a bit flaky

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#522]
Jack was unable to register for habitica twice before it succeeded on the third attempt.
Apparently, vas had a similar experience.

It looks like the correct auth tokens were not passed in properly

```
2017-09-19 19:23:37,296:DEBUG:139665894012672:START POST /habiticaRegister
2017-09-19 19:23:37,297:DEBUG:139665894012672:habitica registration request {u'regConfig
': {u'username': u'jacksullivan'}, u'user': u'<redacted>'} from user = <LocalR
equest: POST https://e-mission.eecs.berkeley.edu/habiticaRegister>
2017-09-19 19:23:37,297:DEBUG:139665894012672:Using OAuth2Client to verify id token of l ength 900 from android phones
2017-09-19 19:23:37,298:DEBUG:139665894012672:Using OAuth2Client to verify id token of l ength 900 from android phones using old token
2017-09-19 19:23:37,299:DEBUG:139665894012672:Using OAuth2Client to verify id token from iOS phones
2017-09-19 19:23:37,300:DEBUG:139665894012672:Using OAuth2Client to verify id token from newer iOS phones
2017-09-19 19:23:37,301:DEBUG:139665894012672:{...'email_verified': True, ..., u'email': u'jack.sullivan@gmail.com',...}
2017-09-19 19:23:37,301:DEBUG:139665894012672:Found user email jack.sullivan@gmail.com
2017-09-19 19:23:37,465:DEBUG:139665894012672:generated id noisyhair21 through dinopass
2017-09-19 19:23:37,466:DEBUG:139665894012672:About to login {'username': u'jacksullivan', 'password': u'noisyhair21', 'email': u'noisyhair21@save.world'}
2017-09-19 19:23:37,498:DEBUG:139665894012672:response = <Response [401]>
2017-09-19 19:23:37,499:DEBUG:139665894012672:About to register {'username': u'jacksulli
van', 'password': u'noisyhair21', 'confirmPassword': u'noisyhair21', 'email': u'noisyhair21@save.world'}
2017-09-19 19:23:37,525:ERROR:139665894012672:Exception while trying to login/signup!
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/net/ext_service/habitica/proxy.py", line 55, in habiticaRegister
    user_dict = newHabiticaUser(username, email, password, our_uuid)
  File "/mnt/e-mission/e-mission-server/emission/net/ext_service/habitica/proxy.py", line 104, in newHabiticaUser
    u.raise_for_status()
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
2017-09-19 19:23:37,526:DEBUG:139665894012672:END POST /habiticaRegister 87b60828-d7a2-4290-a43a-17144fc83494 0.230180025101
```

```
2017-09-19 19:23:48,810:DEBUG:139665885619968:START POST /habiticaRegister
2017-09-19 19:23:48,811:DEBUG:139665885619968:habitica registration request {u'regConfig
': {u'username': u'jacksullivan'}, <redacted>} from user = <LocalR
equest: POST https://e-mission.eecs.berkeley.edu/habiticaRegister>
2017-09-19 19:23:48,811:DEBUG:139665885619968:Using OAuth2Client to verify id token of l ength 900 from android phones
2017-09-19 19:23:48,812:DEBUG:139665885619968:Using OAuth2Client to verify id token of l ength 900 from android phones using old token
2017-09-19 19:23:48,813:DEBUG:139665885619968:Using OAuth2Client to verify id token from iOS phones
2017-09-19 19:23:48,814:DEBUG:139665885619968:Using OAuth2Client to verify id token from newer iOS phones
2017-09-19 19:23:48,815:DEBUG:139665885619968:{... u'email_verified': True, ..., u'email': u'jack.sullivan@gmail.com', ...}
2017-09-19 19:23:48,815:DEBUG:139665885619968:Found user email jack.sullivan@gmail.com
2017-09-19 19:23:48,893:DEBUG:139665885619968:generated id slimyhelp41 through dinopass
2017-09-19 19:23:48,895:DEBUG:139665885619968:About to login {'username': u'jacksullivan', 'password': u'slimyhelp41', 'email': u'slimyhelp41@save.world'}
2017-09-19 19:23:48,918:DEBUG:139665885619968:response = <Response [401]>
2017-09-19 19:23:48,919:DEBUG:139665885619968:About to register {'username': u'jacksullivan', 'password': u'slimyhelp41', 'confirmPassword': u'slimyhelp41', 'email': u'slimyhel p41@save.world'}
2017-09-19 19:23:48,942:ERROR:139665885619968:Exception while trying to login/signup!
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/net/ext_service/habitica/proxy.py", line 55, in habiticaRegister
    user_dict = newHabiticaUser(username, email, password, our_uuid)
  File "/mnt/e-mission/e-mission-server/emission/net/ext_service/habitica/proxy.py", line 104, in newHabiticaUser
    u.raise_for_status()
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
2017-09-19 19:23:48,943:DEBUG:139665885619968:END POST /habiticaRegister 87b60828-d7a2-4290-a43a-17144fc83494 0.133029937744
```

Similar third failure with 

```
2017-09-19 19:23:59,905:DEBUG:139665877227264:About to register {'username': u'jacksullivan', 'password': u'mushycoal35', 'confirmPassword': u'mushycoal35', 'email': u'mushycoa l35@save.world'}
```

And then success after he changed his username.

```
2017-09-19 19:24:25,399:DEBUG:139665868834560:About to register {'username': u'jack.sullivan@gmail.com', 'password': <redacted>, 'confirmPassword': <redacted>', 'email': <redacted>@save.world'}
```

**Comment by shankari** [comment]
The related error is

```
/**
 * @apiDefine NotAuthorized
 * @apiError NotAuthorized The client is not authorized to make this request.
 *
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 401 Unauthorized
 *     {
 *       "error": "NotAuthorized",
 *       "message": "Not authorized."
 *     }
 */
export const NotAuthorized = common.errors.NotAuthorized;
```

That sounds like it is an error in the client key. Which is pretty bizarre because that is a static value that is read once from the json file.

**Comment by shankari** [comment]
suggestions for investigation - try to send an API request without the API key and confirm this is the error returned.
print the client key used before sending the request
send a bunch of registration calls (stress test) and see if we can reproduce this

**Comment by shankari** [comment]
poking around in the habitica database, I see that there is already a user `jacksullivan`  who was created at 5:32 UTC.

```
> db.users.findOne({"auth.local.username": "jacksullivan"})
{
        "_id" : "2b0c05d9-6cc9-49f3-ae50-a31b1e7332b6",
        "pushDevices" : [ ],
        "extra" : {
        },
        "auth" : {
                "timestamps" : {
                        "loggedin" : ISODate("2017-09-19T05:32:59.647Z"),
                        "created" : ISODate("2017-09-19T05:32:59.647Z")
                },
                "local" : {
                        "username" : "jacksullivan",
                        "lowerCaseUsername" : "jacksullivan",
                        "email" : "jack.sullivan@gmail.com",
                        "salt" : "2a8dae4163",
                        "hashed_password" : "62cd08cbb2edae66e1d00a8d5f4156fe26c75b18"
                },
                "facebook" : {

                }
        },
        "apiToken" : "d939ba3e-4c06-4d80-8aef-46dcb9e8bd16",
        "__v" : 0
}
```

and user `jack.sullivan@gmail.com` was created much later. So maybe jack had tried to login directly to habitica before and it had only partially succeeded and then the registration failed because of the duplicate username?

```
> db.users.findOne({"auth.local.username": "jack.sullivan@gmail.com"})
{
        "_id" : "266369b5-504a-467f-b01e-922a11e99bf7",
        "pushDevices" : [ ],
        "extra" : {

        },
        "auth" : {
                "timestamps" : {
                        "loggedin" : ISODate("2017-09-22T20:27:49.320Z"),
                        "created" : ISODate("2017-09-19T19:26:21.315Z")
                },
                "local" : {
                        "username" : "jack.sullivan@gmail.com",
                        "lowerCaseUsername" : "jack.sullivan@gmail.com",
                        "email" : "<redacted>@save.world",
                        "salt" : "17f88d3eac",
                        "hashed_password" : "0e3d2eaab3a14340eec8cd704f2eab00f4e90f90"
                },
                "facebook" : {

                }
        },
        "apiToken" : "6cd55e64-21d3-4fbb-bd5c-bdf699548e77",
        "__v" : 3
}
```
