### ISSUE TITLE
Error in installing bower

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-server#586]
Whenever I try to install bower,
```
$ sudo npm install bower -g
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
+ bower@1.8.4
updated 1 package in 3.767s
```
 and then 
```
$ bower -v
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/deepali/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Configstore.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at new Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:45)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by shankari** [comment]
The first message is just a warning - bower is clearly installed.
For the second, it looks like a permission error opening a configuration file.
Did you try searching for the error message?

**Comment by shankari** [comment]
Note that during setup, you are primarily interacting with third party software - e.g. `node`, `npm`, `bower`, etc. So if you have issues, you may want to search their documentation first.

**Comment by deepalics0044** [comment]
Also
```
~$ sudo bower install --allow-root
bower ENOENT        No bower.json present
```

**Comment by deepalics0044** [comment]
Issue resolved using,
```
~$sudo chown -R $USER:$GROUP ~/.npm
deepali@deepali-HP-Pro-3090-Microtower-PC:~$ sudo chown -R $USER:$GROUP ~/.config
deepali@deepali-HP-Pro-3090-Microtower-PC:~$ bower -v
1.8.4
deepali@deepali-HP-Pro-3090-Microtower-PC:~$ 

```

**Comment by shankari** [comment]
Closing issue
