### ISSUE TITLE
Running pipe analysis - "Error while inferring modes, timestamp is unchanged"

### ISSUE THREAD

**Issue by asiripanich** [e-mission/e-mission-server#591]
I’m getting the following error when I ran pipeline analysis for any user. Any advice?

 
```

(emission) root@f13f9bdda163:/usr/src/app# ./e-mission-py.bash bin/debug/intake_single_user.py -e a.siripanich@unsw.edu.au

Connecting to database URL mongo-e-mission-server

analysis.debug.conf.json not configured, falling back to sample, default configuration

google maps key not configured, falling back to nominatim

nominatim not configured either, place decoding must happen on the client

ERROR:root:habitica not configured, game functions not supported

Traceback (most recent call last):

  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>

    key_file = open('conf/net/ext_service/habitica.json')

FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'

2018-07-24T06:04:45.111528+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: moving to long term**********

2018-07-24T06:05:28.027680+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: filter accuracy if needed**********

2018-07-24T06:05:28.035104+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: segmenting into trips**********

2018-07-24T06:07:50.223928+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: segmenting into sections**********

2018-07-24T06:07:55.799509+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: smoothing sections**********

/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py:891: UserWarning: DataFrame columns are not unique, some columns will be omitted.

  "columns will be omitted.", UserWarning)

2018-07-24T06:08:00.828184+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: cleaning and resampling timeline**********

2018-07-24T06:08:18.689330+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: inferring transportation mode**********

Error while inferring modes, timestamp is unchanged

Traceback (most recent call last):

  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 41, in predict_mode

    mip.runPredictionPipeline(user_id, time_query)

  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 136, in runPredictionPipeline

    self.loadModelStage()

  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 153, in loadModelStage

    self.model = seedp.ModeInferencePipelineMovesFormat.loadModel()

  File "/usr/src/app/emission/analysis/classification/inference/mode/seed/pipeline.py", line 93, in loadModel

    fd = open(SAVED_MODEL_FILENAME, "r")

FileNotFoundError: [Errno 2] No such file or directory: 'seed_model.json'

2018-07-24T06:08:18.746617+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: checking active mode trips to autocheck habits**********

2018-07-24T06:08:18.752688+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: storing views to cache**********
```

**Comment by shankari** [comment]
The first error is actually a warning, not an error. It basically says that you don't have the habitica integration configured so the game is not supported. If you don't want to use the game integration, this is not important

```
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
```

**Comment by shankari** [comment]
The second error, however, is real.

```
2018-07-24T06:08:18.689330+00:00**********UUID 14840ca6-92f5-4dd8-823f-90e5eb8ec40d: inferring transportation mode**********
Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 41, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 136, in runPredictionPipeline
    self.loadModelStage()
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 153, in loadModelStage
    self.model = seedp.ModeInferencePipelineMovesFormat.loadModel()
  File "/usr/src/app/emission/analysis/classification/inference/mode/seed/pipeline.py", line 93, in loadModel
    fd = open(SAVED_MODEL_FILENAME, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'seed_model.json'
```

Basically, I introduced decision tree-based mode inference in https://github.com/e-mission/e-mission-server/pull/509, with the associated design decisions documented in https://github.com/e-mission/e-mission-server/issues/508

In order to use the decision tree to infer mode, you first need to train it. In order to train it, you need a training set of ground truthed data. The model generated from that training set is assumed to be stored in a file called `seed_model.json` (https://github.com/e-mission/e-mission-server/issues/508#issuecomment-314984947)

If there is no such model, the mode inference fails, for obvious reasons.

If you have such a training dataset, you can generate a `seed_model.json` from it (https://github.com/e-mission/e-mission-server/blob/master/bin/analysis/create_static_model.py). Note that the script as written assumes that the training dataset is in moves format because that is the format that my training dataset is in. If you have training data in e-mission format, you will need to extend  
`emission/analysis/classification/inference/mode/pipeline.py` (`ModeInferencePipeline`) to generate and save models as well, and call that instead.

If you don't have such a training dataset, you can request me to send you my `seed_model.json`. I cannot share raw data, but the model is an aggregate, so I can share it.

Alternatively, you can merge the GIS-based mode inference (https://github.com/e-mission/e-mission-server/pull/578) into your local repository and use that instead. It does not require a training dataset or a model since it uses GIS matching based rules directly.

**Comment by shankari** [comment]
From https://github.com/e-mission/e-mission-server/issues/591#issuecomment-408580196
> The second error, however, is real.

Just to clarify, this error is real only if you want mode inference to distinguish between walk, bike, bus, car, train. If you don't need mode inference, or only need to distinguish between walk, bike and motorized, then you can ignore this error as well.

**Comment by asiripanich** [comment]
Understood. Thank you :) 
Will email you to get the model.
