### ISSUE TITLE
test data not display

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-server#605]
Hi,

I have followed the steps to load the `test_july_22`.

I have found that the test data will not show on the phone.

Here is the output of the user that the data will not display.

```
Connecting to database URL mongo-e-mission-server
emission/tests/data/real_examples/shankari_2015-07-22
Loading file emission/tests/data/real_examples/shankari_2015-07-22
After registration, atton16@gmail.com -> c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a
```

```
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2018-10-19T10:12:47.471165+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: moving to long term**********
2018-10-19T10:12:47.525179+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: filter accuracy if needed**********
2018-10-19T10:12:47.531118+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: segmenting into trips**********
2018-10-19T10:12:47.576480+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: segmenting into sections**********
2018-10-19T10:12:47.583832+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: smoothing sections**********
2018-10-19T10:12:47.590957+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: cleaning and resampling timeline**********
2018-10-19T10:12:47.600428+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: inferring transportation mode**********
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
2018-10-19T10:12:47.995068+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: checking active mode trips to autocheck habits**********
2018-10-19T10:12:47.997367+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: storing views to cache**********
```

Additionally, here is the output of the user that the data display correctly.

```
Connecting to database URL mongo-e-mission-server
emission/tests/data/real_examples/shankari_2015-07-22
Loading file emission/tests/data/real_examples/shankari_2015-07-22
After registration, rciti.emission@gmail.com -> 3d86b87f-b956-4aeb-825b-dde668673963
```

```
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2018-10-19T10:16:09.258952+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: moving to long term**********
2018-10-19T10:16:10.237556+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: filter accuracy if needed**********
2018-10-19T10:16:10.242615+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: segmenting into trips**********
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:119: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last5MinsDistances = %s with length %d" % (last5MinsDistances.as_matrix(), len(last5MinsDistances)))
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:121: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last10PointsDistances = %s with length %d, shape %s" % (last10PointsDistances.as_matrix(),
2018-10-19T10:16:17.944574+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: segmenting into sections**********
2018-10-19T10:16:18.794647+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: smoothing sections**********
/usr/src/app/emission/analysis/intake/cleaning/cleaning_methods/jump_smoothing.py:113: FutureWarning: 'argmin' is deprecated, use 'idxmin' instead. The behavior of 'argmin'
will be corrected to return the positional minimum in the future.
Use 'series.values.argmin' to get the position of the minimum now.
  retVal = non_cluster_segments.distance.argmin()
/usr/src/app/emission/analysis/intake/cleaning/location_smoothing.py:55: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  point_list = [ad.AttrDict(row) for row in points_df.to_dict('records')]
/usr/src/app/emission/analysis/intake/cleaning/location_smoothing.py:271: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  filled_df = pd.concat([filled_df, fill_df])
2018-10-19T10:16:19.687097+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: cleaning and resampling timeline**********
2018-10-19T10:16:22.069293+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: inferring transportation mode**********
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
2018-10-19T10:16:22.318821+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: checking active mode trips to autocheck habits**********
2018-10-19T10:16:22.321091+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: storing views to cache**********
```

Can you please help me understand the output and perhaps help us identify the error?

Thank you.

**Comment by atton16** [comment]
Also, the `test_july_22` will not display on devapp. Do you have any comments?

**Comment by shankari** [comment]
> Also, the `test_july_22` will not display on devapp. Do you have any comments?

Not sure why you expected this to work. From https://github.com/e-mission/e-mission-server/issues/605#issue-372222746, you loaded the data as users `atton16@gmail.com` and `rciti.emission@gmail.com`, not `test_july_22`, so you would not expect to see data for `test_july_22`

**Comment by atton16** [comment]
> > Also, the `test_july_22` will not display on devapp. Do you have any comments?
> 
> Not sure why you expected this to work. From [#605 (comment)](https://github.com/e-mission/e-mission-server/issues/605#issue-372222746), you loaded the data as users `atton16@gmail.com` and `rciti.emission@gmail.com`, not `test_july_22`, so you would not expect to see data for `test_july_22`

Oh, I am sorry for misleading you. 

We have two setup

1. Dev app, I load data directly into `test_july_22` user. The data does not appear.

2. Production app, I load data into two users `atton16@gmail.com` and `rciti.emission@gmail.com`, respectively. The data only display on the second user. However, when I load into the first user, `atton16@gmail.com` I do not see any data appear on my phone. So, I try to load into another user, `rciti.emission@gmail.com` (at a different time period), it somehow just work.

**Comment by shankari** [comment]
You may find this document on the pipeline useful - https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/pipeline_details.md

**Comment by atton16** [comment]
> hm. I just tried the same data for two separate users into my development environment and it loaded just fine. `stdout` doesn't really give much detail into what is going on; what does the log show?

Here is the log on development environment:
```
Connecting to database URL ems-mongo
emission/tests/data/real_examples/shankari_2015-07-22
Loading file emission/tests/data/real_examples/shankari_2015-07-22
After registration, test_july_22 -> fdc2f0eb-f527-42ba-ac58-5a54ac395946
Finished loading 0 entries into the usercache and 1906 entries into the timeseries
```

```
Connecting to database URL ems-mongo
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2018-10-22T09:21:22.008443+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: moving to long term**********
2018-10-22T09:21:22.064207+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: filter accuracy if needed**********
2018-10-22T09:21:22.118431+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: segmenting into trips**********
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:119: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last5MinsDistances = %s with length %d" % (last5MinsDistances.as_matrix(), len(last5MinsDistances)))
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:121: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last10PointsDistances = %s with length %d, shape %s" % (last10PointsDistances.as_matrix(),
2018-10-22T09:21:49.611568+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: segmenting into sections**********
2018-10-22T09:21:52.087046+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: smoothing sections**********
/usr/src/app/emission/analysis/intake/cleaning/cleaning_methods/jump_smoothing.py:113: FutureWarning: 'argmin' is deprecated, use 'idxmin' instead. The behavior of 'argmin'
will be corrected to return the positional minimum in the future.
Use 'series.values.argmin' to get the position of the minimum now.
  retVal = non_cluster_segments.distance.argmin()
/usr/src/app/emission/analysis/intake/cleaning/location_smoothing.py:55: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  point_list = [ad.AttrDict(row) for row in points_df.to_dict('records')]
2018-10-22T09:21:54.985989+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: cleaning and resampling timeline**********
2018-10-22T09:22:01.015552+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: inferring transportation mode**********
/opt/conda/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.19.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/opt/conda/lib/python3.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.19.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
2018-10-22T09:22:02.070543+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: checking active mode trips to autocheck habits**********
2018-10-22T09:22:02.078324+00:00**********UUID fdc2f0eb-f527-42ba-ac58-5a54ac395946: storing views to cache**********
```

**Comment by atton16** [comment]
> wrt [#605 (comment)](https://github.com/e-mission/e-mission-server/issues/605#issuecomment-431682726),
> 
> the email <-> uuid mapping is
> 
> ```
> $ ./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py emission/tests/data/real_examples/shankari_2015-07-22 atton16@gmail.com
> storage not configured, falling back to sample, default configuration
> Connecting to database URL localhost
> emission/tests/data/real_examples/shankari_2015-07-22
> Loading file emission/tests/data/real_examples/shankari_2015-07-22
> After registration, atton16@gmail.com -> 30146243-1df5-4659-8b7c-e76eab4766cf
> (emission) C02KT61MFFT0:e-mission-server shankari$ ./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py emission/tests/data/real_examples/shankari_2015-07-22 rciti.emission@gmail.com
> storage not configured, falling back to sample, default configuration
> Connecting to database URL localhost
> emission/tests/data/real_examples/shankari_2015-07-22
> Loading file emission/tests/data/real_examples/shankari_2015-07-22
> After registration, rciti.emission@gmail.com -> ca8dc510-4800-4908-9166-c2c7c55c2f64
> ```
> And each user has 6 cleaned trips, so everything seems to be fine...
> 
> ```
> In [35]: ts1 = esta.TimeSeries.get_time_series(UUID("30146243-1df5-4659-8b7c-e76eab4766c
>     ...: f"))
> 
> In [36]: ct_df1 = ts1.get_data_df("analysis/cleaned_trip", time_query=None)
> 
> In [37]: len(ct_df1)
> Out[37]: 6
> 
> In [38]: ts2 = esta.TimeSeries.get_time_series(UUID("ca8dc510-4800-4908-9166-c2c7c55c2f6
>     ...: 4"))
> 
> In [39]: ct_df2 = ts2.get_data_df("analysis/cleaned_trip", time_query=None)
> 
> In [40]: len(ct_df2)
> Out[40]: 6
> ```

How do you get the detailed output like this one?

Thanks

**Comment by shankari** [comment]
> Here is the log on development environment:

This is not really the full log (https://github.com/orgs/e-mission/teams/em-workshop-2018/discussions/3/comments/6)

> How do you get the detailed output like this one?

ipython. You may want to watch the video for the second workshop session - I go through examples of manipulating the data in both ipython and ipython notebook, step by step.
