### ISSUE TITLE
Analysis result not updated

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-server#606]
Hi,

I have set the cronjob for pipeline analysis to run once every **hour**.

The pipeline appears to run properly (with 3 workers) based on the log.

However, the analysis result does not show up.

Please help me investigate this problem.

Here is the log from the latest run.

```
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2018-10-22T09:00:03.969655+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: moving to long term**********
2018-10-22T09:00:04.036855+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: filter accuracy if needed**********
2018-10-22T09:00:04.043923+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: segmenting into trips**********
2018-10-22T09:00:04.158078+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: segmenting into sections**********
2018-10-22T09:00:04.315768+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: smoothing sections**********
2018-10-22T09:00:04.475972+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: cleaning and resampling timeline**********
2018-10-22T09:00:04.793538+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: inferring transportation mode**********
2018-10-22T09:00:04.952992+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: checking active mode trips to autocheck habits**********
2018-10-22T09:00:04.956236+00:00**********UUID 3d86b87f-b956-4aeb-825b-dde668673963: storing views to cache**********
2018-10-22T09:00:08.738470+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: moving to long term**********
2018-10-22T09:00:08.806153+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: filter accuracy if needed**********
2018-10-22T09:00:08.812675+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: segmenting into trips**********
2018-10-22T09:00:08.907604+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: segmenting into sections**********
2018-10-22T09:00:09.082738+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: smoothing sections**********
2018-10-22T09:00:09.258132+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: cleaning and resampling timeline**********
2018-10-22T09:00:09.589682+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: inferring transportation mode**********
2018-10-22T09:00:09.765693+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: checking active mode trips to autocheck habits**********
2018-10-22T09:00:09.769073+00:00**********UUID be0a595c-9836-454e-b9c7-9b7db6a61a18: storing views to cache**********
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2018-10-22T09:00:03.984259+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: moving to long term**********
2018-10-22T09:00:03.998238+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: filter accuracy if needed**********
2018-10-22T09:00:04.005897+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: segmenting into trips**********
2018-10-22T09:00:04.051121+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: segmenting into sections**********
2018-10-22T09:00:04.212317+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: smoothing sections**********
2018-10-22T09:00:04.368695+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: cleaning and resampling timeline**********
2018-10-22T09:00:04.686928+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: inferring transportation mode**********
2018-10-22T09:00:04.846270+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: checking active mode trips to autocheck habits**********
2018-10-22T09:00:04.849464+00:00**********UUID 292bad80-9351-4612-bec7-6342b7253125: storing views to cache**********
2018-10-22T09:00:04.856472+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: moving to long term**********
2018-10-22T09:00:04.914245+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: filter accuracy if needed**********
2018-10-22T09:00:04.921224+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: segmenting into trips**********
2018-10-22T09:00:05.033812+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: segmenting into sections**********
2018-10-22T09:00:05.202724+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: smoothing sections**********
2018-10-22T09:00:05.389395+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: cleaning and resampling timeline**********
2018-10-22T09:00:05.743486+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: inferring transportation mode**********
2018-10-22T09:00:05.914321+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: checking active mode trips to autocheck habits**********
2018-10-22T09:00:05.917392+00:00**********UUID c713b0af-5bd7-40fc-9f6d-7e18a4bcb33a: storing views to cache**********
2018-10-22T09:00:11.593984+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: moving to long term**********
2018-10-22T09:00:11.675666+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: filter accuracy if needed**********
2018-10-22T09:00:11.682144+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: segmenting into trips**********
2018-10-22T09:00:11.781429+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: segmenting into sections**********
2018-10-22T09:00:11.964298+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: smoothing sections**********
2018-10-22T09:00:12.172250+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: cleaning and resampling timeline**********
2018-10-22T09:00:12.543739+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: inferring transportation mode**********
2018-10-22T09:00:12.730328+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: checking active mode trips to autocheck habits**********
2018-10-22T09:00:12.733511+00:00**********UUID aa94231c-b5aa-46dc-9b52-a01873693397: storing views to cache**********
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2018-10-22T09:00:03.984255+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: moving to long term**********
2018-10-22T09:00:04.089749+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: filter accuracy if needed**********
2018-10-22T09:00:04.096452+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: segmenting into trips**********
2018-10-22T09:00:04.316943+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: segmenting into sections**********
2018-10-22T09:00:04.475596+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: smoothing sections**********
2018-10-22T09:00:04.634466+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: cleaning and resampling timeline**********
2018-10-22T09:00:04.952782+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: inferring transportation mode**********
2018-10-22T09:00:05.121245+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: checking active mode trips to autocheck habits**********
2018-10-22T09:00:05.124404+00:00**********UUID 3362b999-656e-4457-b8ef-ff2e097c709b: storing views to cache**********
2018-10-22T09:00:14.700276+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: moving to long term**********
2018-10-22T09:00:15.163984+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: filter accuracy if needed**********
2018-10-22T09:00:15.171418+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: segmenting into trips**********
2018-10-22T09:00:15.517037+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: segmenting into sections**********
2018-10-22T09:00:15.792457+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: smoothing sections**********
2018-10-22T09:00:16.058651+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: cleaning and resampling timeline**********
2018-10-22T09:00:16.699649+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: inferring transportation mode**********
2018-10-22T09:00:17.094139+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: checking active mode trips to autocheck habits**********
2018-10-22T09:00:17.097792+00:00**********UUID d5f331ed-d0bd-4d15-ae46-3a79871876fa: storing views to cache**********
```

**Comment by shankari** [comment]
https://github.com/orgs/e-mission/teams/em-workshop-2018/discussions/3/comments/6
