### ISSUE TITLE
Ground Truth Matching Key Error with stopStartRadius

### ISSUE THREAD

**Issue by b-i-l-l-c-a-o** [e-mission/e-mission-server#614]
While running the pipeline, I get the following error. However, it doesn't stop the pipeline from continuing.

```
Sectioning failed for user 1777a6a2-544a-4e38-8ab9-0b36b7062ce6
Traceback (most recent call last):
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 52, in segment_current_sections
    segment_trip_into_sections(user_id, trip_entry, trip_entry.data.source)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 85, in segment_trip_into_sections
    segmentation_points = shcmsm.segment_into_sections(ts, distance_from_place, time_query)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 170, in segment_into_sections
    self.squish_stops(motion_changes, section_list)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 202, in squish_stops
    STOP_DISTANCE_THRESHOLD = max(eac.get_config()["section.startStopRadius"],
KeyError: 'section.startStopRadius'
```

**Comment by b-i-l-l-c-a-o** [comment]
`
Sectioning failed for user 1777a6a2-544a-4e38-8ab9-0b36b7062ce6
Traceback (most recent call last):
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 52, in segment_current_sections
    segment_trip_into_sections(user_id, trip_entry, trip_entry.data.source)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 85, in segment_trip_into_sections
    segmentation_points = shcmsm.segment_into_sections(ts, distance_from_place, time_query)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 170, in segment_into_sections
    self.squish_stops(motion_changes, section_list)
  File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 202, in squish_stops
    STOP_DISTANCE_THRESHOLD = max(eac.get_config()["section.startStopRadius"],
KeyError: 'section.startStopRadius'
`

**Comment by shankari** [comment]
as you can see, this is trying to get the section.startStopRadius property from the config.
If you look at the pull request that you merged, you will see that this is added to the analysis configuration as part of the PR
https://github.com/e-mission/e-mission-server/pull/578/files#diff-724d9f66af98df26b1b166393db70ddf

Is your analysis configuration updated?

**Comment by b-i-l-l-c-a-o** [comment]
`Sectioning failed for user 1777a6a2-544a-4e38-8ab9-0b36b7062ce6 Traceback (most recent call last): File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 52, in segment_current_sections segment_trip_into_sections(user_id, trip_entry, trip_entry.data.source) File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation.py", line 85, in segment_trip_into_sections segmentation_points = shcmsm.segment_into_sections(ts, distance_from_place, time_query) File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 170, in segment_into_sections self.squish_stops(motion_changes, section_list) File "/home/ubuntu/e-mission-server/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 202, in squish_stops STOP_DISTANCE_THRESHOLD = max(eac.get_config()["section.startStopRadius"], KeyError: 'section.startStopRadius`
