### ISSUE TITLE
Server returning error on phone 

### ISSUE THREAD

**Issue by valin1** [e-mission/e-mission-server#621]
Sam is getting a HTTP400 error when she tries to call the getSuggestion function and you mentioned that the server is returning an error. So, I went on the app and tried to load a suggestion again (01/08), but when I looked into webserver-errors.log, I only get errors up to 01/06. 
```
2018-12-04 00:13:19,179:ERROR:140703992637184:old style duration 41.095603704452515 != timer based duration 0.005175009369850159
2018-12-12 19:15:37,693:ERROR:139954622416640:old style duration 191.65300822257996 != timer based duration 0.10201038978993893
2018-12-16 02:54:30,844:ERROR:139954614023936:old style duration 36.60388684272766 != timer based duration 0.003043627366423607
2018-12-16 03:08:58,263:ERROR:139954630809344:old style duration 46.219382524490356 != timer based duration 0.015524160116910934
2018-12-19 06:25:01,355:ERROR:139954605631232:old style duration 128.1040813922882 != timer based duration 0.1539552565664053
2018-12-20 00:02:28,824:ERROR:139954353055488:old style duration 183.64664673805237 != timer based duration 0.3211926035583019
2018-12-20 22:40:51,604:ERROR:139954630809344:old style duration 208.92368984222412 != timer based duration 0.10112249478697777
2018-12-22 17:12:57,419:ERROR:139954361448192:old style duration 27.654802560806274 != timer based duration 0.03603575564920902
2018-12-31 21:36:02,017:ERROR:139954630809344:old style duration 21.564500331878662 != timer based duration 0.019800933077931404
2019-01-03 01:27:07,214:ERROR:139954395019008:old style duration 0.7161393165588379 != timer based duration 0.004084000363945961
2019-01-05 22:33:27,824:ERROR:140159395813120:old style duration 0.5120875835418701 != timer based duration 0.0009740926325321198
2019-01-06 03:28:13,211:ERROR:140159643354880:old style duration 183.79750967025757 != timer based duration 0.12999366782605648
```
I looked into webserver.log and it seems like it is trying to get a suggestion, but it doesn't seem to output the suggestion in the logs like what I had in the getSuggestion function. Also, in the logs, it seems like it ends the call after getting the user_uuid, which makes me think that there was an error in calling the function, but I didn't change the function name and the input for the suggestion on the Recommend page, only takes in the uuid.  

```
2019-01-08 19:32:31,783:DEBUG:140159379027712:START POST /suggestion_sys
2019-01-08 19:32:31,783:DEBUG:140159379027712:Called suggestion
2019-01-08 19:32:31,783:DEBUG:140159379027712:methodName = token_list, returning <class 'emission.net.auth.token_list.TokenListMethod'>
2019-01-08 19:32:31,783:DEBUG:140159379027712:Using the TokenListMethod to verify id token vwpdnT6r of length 8 against list ['8QU4GCAZ', 'sGSqEvFY', 'GjgJfa8p', 'D59gab8t', '2Fw2KUxb', 'TpLet8KX', 'CHDHbvbt', '4TkBW9WU', '99UE6UsX', 'vwpdnT6r']...
2019-01-08 19:32:31,783:DEBUG:140159379027712:Found match for token vwpdnT6r of length 8
2019-01-08 19:32:31,784:DEBUG:140159379027712:retUUID = 89040eaa-6142-41b8-930a-afb35672306e
2019-01-08 19:32:31,784:DEBUG:140159379027712:user_uuid 89040eaa-6142-41b8-930a-afb35672306e
2019-01-08 19:32:31,784:DEBUG:140159379027712:END POST /suggestion_sys 89040eaa-6142-41b8-930a-afb35672306e 0.0017092227935791016 
2019-01-08 19:32:31,786:DEBUG:140159379027712:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2019-01-08 19:32:31,786:DEBUG:140159379027712:entry was fine, no need to fix it
2019-01-08 19:32:31,786:DEBUG:140159379027712:Inserting entry Entry({'_id': ObjectId('5c34facf9258b9153a4ab2cb'), 'user_id': UUID('89040eaa-6142-41b8-930a-afb35672306e'), 'metadata': Metadata({'key': 'stats/server_api_time', 'platform': 'server', 'write_ts': 1546975951.7851233, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2019, 'month': 1, 'day': 8, 'hour': 11, 'minute': 32, 'second': 31, 'weekday': 1, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2019-01-08T11:32:31.785123-08:00'}), 'data': {'name': 'POST_/suggestion_sys', 'ts': 1546975951.7848642, 'reading': 0.0017092227935791016}}) into timeseries
2019-01-08 19:32:31,788:DEBUG:140159379027712:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2019-01-08 19:32:31,788:DEBUG:140159379027712:entry was fine, no need to fix it
2019-01-08 19:32:31,788:DEBUG:140159379027712:Inserting entry Entry({'_id': ObjectId('5c34facf9258b9153a4ab2cc'), 'user_id': UUID('89040eaa-6142-41b8-930a-afb35672306e'), 'metadata': Metadata({'key': 'stats/server_api_time', 'platform': 'server', 'write_ts': 1546975951.787097, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2019, 'month': 1, 'day': 8, 'hour': 11, 'minute': 32, 'second': 31, 'weekday': 1, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2019-01-08T11:32:31.787097-08:00'}), 'data': {'name': 'POST_/suggestion_sys_cputime', 'ts': 1546975951.7848642, 'reading': 0.001608245074748993}}) into timeseries
```

**Comment by shankari** [comment]
obvious questions first:
- have you pulled your changes to the server?
- have you restarted the server after that?
- what do you see on stdout/stderr? This is set in your `supervisord.conf` (`stdout_logfile` and `stderr_logfile`)

**Comment by valin1** [comment]
Yes, this was all after pulling changes and restarting the server. I am not sure where stdout_logfile is located?

**Comment by shankari** [comment]
look at `supervisord.conf`

**Comment by shankari** [comment]
or if you are not running the server through supervisord, but directly in screen, then connect to the screen and look at the console

**Comment by ecvick85** [comment]
this is the stdout from screen

```
File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/socket.py", line 583, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object
socket.error 'cannot read from timed out object'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/wsgi.py", line 136, in respond
    self.write(chunk)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/wsgi.py", line 215, in write
    self.req.send_headers()
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 1083, in send_headers
    self.rfile.read(remaining)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 315, in read
    data = self.rfile.read(size)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/_pyio.py", line 1001, in read
    return self._read_unlocked(size)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/_pyio.py", line 1041, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/socket.py", line 583, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object
START 2019-01-09 00:09:42.859016 GET /
END 2019-01-09 00:09:42.859574 GET /  0.0004832744598388672
START 2019-01-09 00:10:24.695659 POST /usercache/put
old style duration 9.852147102355957 != timer based duration 0.014630993828177452
END 2019-01-09 00:10:34.550303 POST /usercache/put  9.852147102355957
START 2019-01-09 00:11:07.857886 POST /usercache/put
END 2019-01-09 00:12:38.248936 POST /usercache/put f9875c72-ba39-4c22-ba03-cb2a8e8cabc7 90.3909695148468
```

**Comment by shankari** [comment]
great! now you have found the error. And it has nothing directly to do with emission (look at the stacktrace, there is nothing related to e-mission there).

What do you think you should do next?

**Comment by valin1** [comment]
Is this because we need to update pip or there's too much stuff that the server is trying to read or the file is locked? I looked up some posts that had "raise OSError("cannot read from timed out object")" and "OSError: cannot read from timed out object" and the stack over flow posts had no specific answers to the problem, but a lot of different causes for OSErrors?

**Comment by shankari** [comment]
just to clarify, this is now an example of general server debugging which you should be able to re-use after graduation.

ok, so different `OSError`s are not that useful; we know that this particular `OSError` is related to a timeout, and we know that it is while the server is trying to read something. What are the potential files that the server could read from? Which one of those is it reading from here?

```
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 315, in read
    data = self.rfile.read(size)
```

**Comment by valin1** [comment]
Is there some tool to figure out what files the server is reading from? Because on stack over flow it mentions some tools to check for network congestion, but I am not sure if there's any other way?

**Comment by valin1** [comment]
Nevermind, we fixed it. It had nothing to do the OSError at all, but with a function name.

**Comment by shankari** [comment]
ah, so the last error in the logs is not always the most relevant one. It looks like there was a timeout while communicating with one of the clients, but that should be a transient versus a permanent error. Good job, @ecvick85 !
